### PR TITLE
8315969: compiler/rangechecks/TestRangeCheckHoistingScaledIV.java: make flagless

### PR DESCRIPTION
**Pull request by amosshi**
Backport of [JDK-8315969](https://bugs.openjdk.org/browse/JDK-8315969)
- The change on file `TestRangeCheckHoistingScaledIV.java` is clean, because it is auto done by `git patch` command
- The `test/hotspot/jtreg/ProblemList.txt` file in the original commit is ignored, because the line does not exist
- So this PR can be `considered as clean`

Testing
- Local: Test passed
  - `TestRangeCheckHoistingScaledIV.java`: Test results: passed: 1
- Pipeline: All checks have passed
- Testing Machine: SAP nightlies passed on `2024-06-23`
  - `jtreg_hotspot_tier2`: compiler/rangechecks/TestRangeCheckHoistingScaledIV.java: SUCCESSFUL GitHub 📊⏲ - [4,593 msec]

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8315969](https://bugs.openjdk.org/browse/JDK-8315969) needs maintainer approval

### Issue
 * [JDK-8315969](https://bugs.openjdk.org/browse/JDK-8315969): compiler/rangechecks/TestRangeCheckHoistingScaledIV.java: make flagless (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/752/head:pull/752` \
`$ git checkout pull/752`

Update a local copy of the PR: \
`$ git checkout pull/752` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/752/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 752`

View PR using the GUI difftool: \
`$ git pr show -t 752`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/752.diff">https://git.openjdk.org/jdk21u-dev/pull/752.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/752#issuecomment-2177448355)

### CODE REVIEW

**Comment by TheRealMDoerr** [comment]
I think you need to update the problem list (see Error above).

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by amosshi** [comment]
/approval request "Backporting for parity with 21.0.5-oracle. No risk, test fix. Un-Clean backport. Test passes and SAP nightlies pass on 2024-06-23”

**Pull request closed without merging**
