### PR TITLE
8320575: generic type information lost on mandated parameters of record's compact constructors

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 21.0.6-oracle.

As the CSR for 21 says, I omit the specification changes. 
These make the description more precise. As I understand,
the change brought to 21 is ok with the broader, unchanged 
specification.

The rest applied clean.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8320575](https://bugs.openjdk.org/browse/JDK-8320575) needs maintainer approval
- [x] Change requires CSR request [JDK-8337480](https://bugs.openjdk.org/browse/JDK-8337480) to be approved

### Warning
&nbsp;⚠️ Found leading lowercase letter in issue title for `8320575: generic type information lost on mandated parameters of record's compact constructors`

### Issues
 * [JDK-8320575](https://bugs.openjdk.org/browse/JDK-8320575): generic type information lost on mandated parameters of record's compact constructors (**Bug** - P3 - Approved)
 * [JDK-8337480](https://bugs.openjdk.org/browse/JDK-8337480): generic type information lost on mandated parameters of record's compact constructors (**CSR**)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1026/head:pull/1026` \
`$ git checkout pull/1026`

Update a local copy of the PR: \
`$ git checkout pull/1026` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1026/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1026`

View PR using the GUI difftool: \
`$ git pr show -t 1026`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1026.diff">https://git.openjdk.org/jdk21u-dev/pull/1026.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1026#issuecomment-2396201387)
</details>

### CODE REVIEW

**Review by MBaesken — APPROVED** [review]

**Comment by GoeLin** [comment]
Hi @vincente-romero-oracle, @jddarcy, @weibxiao,
could one of you please verify whether I modified this correctly to match the backport CSR?
Thanks!

**Comment by weibxiao** [comment]
For class Excectable.java, three methods got changed. It seems you only modified one. All comments for the modified methods were not there.

**Comment by GoeLin** [comment]
Hi Weibing, 

thanks for having a look!

Well, the comment of three methods got changed but only one has code changes. At least the public commit https://github.com/openjdk/jdk/commit/7bf1989f59695c3d08b4bd116fb4c022cf9661f4 touches only the code of getGenericParameterTypes().

I omitted the comments on purpose becaus the[ CSR for 21 8337480](https://bugs.openjdk.org/browse/JDK-8337480) does not mention the comment change as the [original one 8321819](https://bugs.openjdk.org/browse/JDK-8321819) does. Also, I read the discussion in the comments like that.

So you are saying you backported all the comments to 21? If so. I'll add them, too.

Thanks, Goetz

**Pull request closed without merging**
