### PR TITLE
8343343: Misc crash dump improvements on more platforms after JDK-8294160

### PR DESCRIPTION
**Pull request by TheRealMDoerr**
Mostly clean backport of [JDK-8343343](https://bugs.openjdk.org/browse/JDK-8343343). PPC64 files use a different frame constructor after [JDK-8290965](https://bugs.openjdk.org/browse/JDK-8290965) (JDK23). Includes [JDK-8343149](https://bugs.openjdk.org/browse/JDK-8343149).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8343149](https://bugs.openjdk.org/browse/JDK-8343149) needs maintainer approval
- [x] [JDK-8343343](https://bugs.openjdk.org/browse/JDK-8343343) needs maintainer approval

### Issues
 * [JDK-8343343](https://bugs.openjdk.org/browse/JDK-8343343): Misc crash dump improvements on more platforms after JDK-8294160 (**Bug** - P4 - Approved)
 * [JDK-8343149](https://bugs.openjdk.org/browse/JDK-8343149): Cleanup os::print_tos_pc on AIX (**Bug** - P4 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1154/head:pull/1154` \
`$ git checkout pull/1154`

Update a local copy of the PR: \
`$ git checkout pull/1154` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1154/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1154`

View PR using the GUI difftool: \
`$ git pr show -t 1154`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1154.diff">https://git.openjdk.org/jdk21u-dev/pull/1154.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1154#issuecomment-2474842609)
</details>

### CODE REVIEW

**Review by MBaesken — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
Thanks for the review! GHA failures on macOS-aarch64 are unrelated.

**Review by MBaesken — APPROVED** [review]

**Comment by TheRealMDoerr** [comment]
/approval request This enhancement may help analyzing crashes. It adds output to hs_err files on some platforms and makes some inspections more reliable. The backport was not difficult to resolve, has been reviewed and tier 1-4 have passed.

**Comment by GoeLin** [comment]
Hi @TheRealMDoerr 
this is rather new and an enhancement. 
What about waiting for April update, so it is live in 24 before we backport?
21.0.7 development starts soon.

**Comment by TheRealMDoerr** [comment]
@GoeLin: Having the `is_readable_pointer` checks is a good thing. This PR only looks large because of harmless refactoring. The modification is already shipped for some platforms with [JDK-8294160](https://bugs.openjdk.org/browse/JDK-8294160) in 21 GA and 17.0.7.
On the other hand, I'm not aware of too many "error occurred during error reporting" issues on the missing platforms, so I can live with shipping it with 21.0.7. I leave the 21u lead maintainers free to decide.

**Pull request closed without merging**
