### PR TITLE
8319673: Few security tests ignore VM flags

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,

This pull request contains a backport of commit [43029006](https://github.com/openjdk/jdk/commit/430290066c23d09166a84f2f6f89e770c6ba04ff) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository. Backport parity with 21.0.5-oracle, the change has been verified, no risk.

The commit being backported was authored by Matthew Donovan on 29 Feb 2024 and was reviewed by Weijun Wang and Hai-May Chao.

The new API `Path resolve(String first, String... more)` was not supported in jdk21u-dev, so I change the line code from `COPY_JDK_DIR.resolve("bin", "java")` to `COPY_JDK_DIR.resolve("bin").resolve("java")` to avoid jdk21 javac generate compile error, and make this backport uncleanly, all other parts are backported cleanly.

The change has been verified locally, test-fix only, no risk.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8319673](https://bugs.openjdk.org/browse/JDK-8319673) needs maintainer approval

### Issue
 * [JDK-8319673](https://bugs.openjdk.org/browse/JDK-8319673): Few security tests ignore VM flags (**Sub-task** - P4 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/830/head:pull/830` \
`$ git checkout pull/830`

Update a local copy of the PR: \
`$ git checkout pull/830` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/830/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 830`

View PR using the GUI difftool: \
`$ git pr show -t 830`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/830.diff">https://git.openjdk.org/jdk21u-dev/pull/830.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/830#issuecomment-2216800593)
</details>

### CODE REVIEW

**Comment by sendaoYan** [comment]
wait

**Comment by sendaoYan** [comment]
wait

**Comment by GoeLin** [comment]
Hi @sendaoYan, what's up with this backport?

**Comment by sendaoYan** [comment]
> Hi @sendaoYan, what's up with this backport?

I think  I just mistake the PR status. I make this PR as ready now.

**Comment by sendaoYan** [comment]
I will verify the jtreg tests then create approval request later.

**Comment by sendaoYan** [comment]
This backport will generate below javac compiler error, cause by new API `Path resolve(String first, String... more)` was not support in jdk21u-dev
Should we integrate this PR first, and then create a new PR to fix the compiler error.

```
/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/security/Security/ConfigFileTest.java:57: error: no suitable method found for resolve(String,String)
    private static Path COPIED_JAVA = COPY_JDK_DIR.resolve("bin", "java");
```

**Comment by sendaoYan** [comment]
GHA report `install some dependencies` failure in macos-aarch64, it seems like envirnmental issue, it's unrelrated to this PR.

**Comment by GoeLin** [comment]
Hi @sendaoYan, 
this is a normal thing happening with backports. We don't file extra bugs for this.
If it was clean before, it is best to push an extra commit on top of the original backport, explain in detail in the PR what and why it was edited, and include a short remark in the approval comment that it had to be adapted to 21. (This hints the person backporting to 17 to base the backport on the 21 commit).

**Comment by sendaoYan** [comment]
> Hi @sendaoYan, this is a normal thing happening with backports. We don't file extra bugs for this. If it was clean before, it is best to push an extra commit on top of the original backport, explain in detail in the PR what and why it was edited, and include a short remark in the approval comment that it had to be adapted to 21. (This hints the person backporting to 17 to base the backport on the 21 commit).

Thanks for the detail advice. I will create a new PR to backport plus fix the compile error.

**Comment by sendaoYan** [comment]
> Thanks for the detail advice. I will create a new PR to backport plus fix the compile error.

The new PR https://github.com/openjdk/jdk21u-dev/pull/1142 has been created, close this as duplicated.

**Comment by GoeLin** [comment]
Hi, you don't need a new pr, just push a fix to this branch. The fix is simple enough, you can just edit it in the web.

**Comment by sendaoYan** [comment]
> Hi, you don't need a new pr, just push a fix to this branch. The fix is simple enough, you can just edit it in the web. Locally, you can check out origin/pr/830 and double-check on it if needed.

Hi, I can't edit the code in the web. Seems like I don't have enough permission.

image

**Comment by sendaoYan** [comment]
> Hi, you don't need a new pr, just push a fix to this branch. The fix is simple enough, you can just edit it in the web. Locally, you can check out origin/pr/830 and double-check on it if needed.

Thanks for your patient advising. This PR has been updated.

**Comment by GoeLin** [comment]
GHA failure of latest run: infra issue, unrelated
error: invalid developer directory '/Applications/Xcode_14.3.1.app/Contents/Developer'

**Review by RealLucy — APPROVED** [review]
LGTM.

**Comment by sendaoYan** [comment]
> LGTM.

Thanks for the review.

/approval request Backport to make several tests receive VM options from jtreg. The change has been verified locally, test-fix only, no risk.

**Comment by sendaoYan** [comment]
Thanks all for the review and approved.

/integrate

**Pull request closed without merging**
