### PR TITLE
8324646: Avoid Class.forName in SecureRandom constructor

### PR DESCRIPTION
**Pull request by olivergillespie**
Hi all,

This pull request contains a backport of commit [8ef918d6](https://github.com/openjdk/jdk/commit/8ef918d6678437a5b351b172bb4cf144eeaa975f) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Oli Gillespie on 9 Feb 2024 and was reviewed by Aleksey Shipilev and Weijun Wang.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8324646](https://bugs.openjdk.org/browse/JDK-8324646) needs maintainer approval

### Issue
 * [JDK-8324646](https://bugs.openjdk.org/browse/JDK-8324646): Avoid Class.forName in SecureRandom constructor (**Enhancement** - P4 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/258/head:pull/258` \
`$ git checkout pull/258`

Update a local copy of the PR: \
`$ git checkout pull/258` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/258/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 258`

View PR using the GUI difftool: \
`$ git pr show -t 258`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/258.diff">https://git.openjdk.org/jdk21u-dev/pull/258.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/258#issuecomment-1941291703)

### CODE REVIEW

**Comment by olivergillespie** [comment]
/approval request Performance improvement in SecureRandom.<init> which I have seen on the hot path. Clean backport, simple change with low risk in my opinion.

**Comment by GoeLin** [comment]
Hi @olivergillespie
As this is an optimization I think it should bake in head for a while. Please label again for the July update, dev starts 27.2..

**Comment by olivergillespie** [comment]
/approval request Performance improvement in SecureRandom, which I have seen on the hot path. Clean backport, simple change with low risk in my opinion (re-requesting now for July update and it has been in tip for a few weeks). Similar to 8324648 which was just approved.

**Review by shipilev — APPROVED** [review]

**Comment by GoeLin** [comment]
@olivergillespie, please back port to 22, too, also, there are failing tests. removing the label

**Comment by olivergillespie** [comment]
Thanks, sorry @GoeLin for not understanding the backport procedure properly. I thought approval came first, before final testing/review etc., my mistake!

Backport to 22 (approval requested): https://github.com/openjdk/jdk22u/pull/98

Tests are now passing after merging from master.

Benchmark results (`make test TEST=micro:org.openjdk.bench.java.security.SecureRandomBench`):

```
Before: 495 ± 6 ns/op
 After:  103 ± 1.6 ns/op
```

Hopefully I didn't miss anything this time, so I'll request approval again - thanks.

**Comment by olivergillespie** [comment]
/approval request Performance improvement in `SecureRandom.<init>`, which I have seen on the hot path. Clean backport, simple change with low risk in my opinion due to small, simple change in only one file (re-requesting now for July update and it has been in tip for a few weeks). Similar to 8324648 which was approved. Update: re-re-requesting after fixing unrelated test failures with merge from master, and added benchmark results (before: 500ns/op, after: 100ns/op).

**Pull request closed without merging**
