### PR TITLE
8320275: assert(_chunk->bitmap().at(index)) failed: Bit not set at index

### PR DESCRIPTION
**Pull request by shipilev**
Nearly clean backport to fix a Loom bug. The uncleanliness is due to `foreign_globals.cpp` context change in `ForeignGlobals::java_calling_convention`, which renamed the argument. I reapplied that hunk by hand.

Additional testing:
 - [x] macos-aarch64-server-fastdebug, `jdk_loom hotspot_loom`
 - [x] linux-aarch64-server-fastdebug, `tier{1,2,3,4}`
 - [x] linux-x86_64-server-fastdebug, `tier{1,2,3,4}`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8323595](https://bugs.openjdk.org/browse/JDK-8323595) needs maintainer approval
- [x] [JDK-8320275](https://bugs.openjdk.org/browse/JDK-8320275) needs maintainer approval

### Issues
 * [JDK-8320275](https://bugs.openjdk.org/browse/JDK-8320275): assert(_chunk-&gt;bitmap().at(index)) failed: Bit not set at index (**Bug** - P3 - Approved)
 * [JDK-8323595](https://bugs.openjdk.org/browse/JDK-8323595): is_aligned(p, alignof(OopT))) assertion fails in Jetty without compressed OOPs (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [0f2c2278](https://git.openjdk.org/jdk21u-dev/pull/131/files/0f2c22780fadb0b3b559a55a3bf95816d727d6ce)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/131/head:pull/131` \
`$ git checkout pull/131`

Update a local copy of the PR: \
`$ git checkout pull/131` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/131/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 131`

View PR using the GUI difftool: \
`$ git pr show -t 131`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/131.diff">https://git.openjdk.org/jdk21u-dev/pull/131.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/131#issuecomment-1877708881)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by shipilev** [comment]
/approval request Nearly clean backport to fix a Loom bug. The uncleanliness is due to foreign_globals.cpp context change in ForeignGlobals::java_calling_convention, which renamed the argument. I reapplied that hunk by hand. Tests pass. The patch is a bit risky, because it touches calling conventions.

**Comment by shipilev** [comment]
/approval 8320275 request (Resubmitting for 21.0.4) Nearly clean backport to fix a Loom bug. The uncleanliness is due to `foreign_globals.cpp` context change in `ForeignGlobals::java_calling_convention`, which renamed the argument. I reapplied that hunk by hand. Tests pass. The patch is a bit risky, because it touches calling conventions. There was no product bugtail after >6 weeks in mainline, including JDK 22 EA testing.

/approval 8323595 request Follow-up for JDK-8320275, fixes the incorrect assert.

**Comment by shipilev** [comment]
Re-tested `all` on Linux aarch64, still fully passes.

/integrate

**Pull request closed without merging**
