### PR TITLE
8320379: C2: Sort spilling/unspilling sequence for better ld/st merging into ldp/stp on AArch64

### PR DESCRIPTION
**Pull request by pengxiaolong**
Backport JDK-8320379: C2: Sort spilling/unspilling sequence for better ld/st merging into ldp/stp on AArch64

### Validation

Tested on AWS Graviton instance by running ```JTREG_KEYWORDS="\!headful & \!external-dep & \!printer" make test TEST=all```, same the test for PR on jdk17, only saw few test failures in CAInterop.java and compiler/intrinsics. 

- CAInterop tests are known intermittently failing tests, it should be fine to ignore. 
- The test failures from compiler/intrinsics has error message "Option 'UseSHA3Intrinsics' is expected to have 'true' value Option 'UseSHA3Intrinsics' should be enabled by default", it seems a bug but not related to the backport, will follow up we need to create a bug.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8320379](https://bugs.openjdk.org/browse/JDK-8320379) needs maintainer approval

### Issue
 * [JDK-8320379](https://bugs.openjdk.org/browse/JDK-8320379): C2: Sort spilling/unspilling sequence for better ld/st merging into ldp/stp on AArch64 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/665/head:pull/665` \
`$ git checkout pull/665`

Update a local copy of the PR: \
`$ git checkout pull/665` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/665/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 665`

View PR using the GUI difftool: \
`$ git pr show -t 665`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/665.diff">https://git.openjdk.org/jdk21u-dev/pull/665.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/665#issuecomment-2150760125)

### CODE REVIEW

**Comment by theRealAph** [comment]
Did you submit a jdk22 backport request?

**Comment by shipilev** [comment]
> Did you submit a jdk22 backport request?

This issue is fixed in 22 originally, so no JDK 22u backport is needed.

Aside: my read of https://mail.openjdk.org/pipermail/jdk-updates-dev/2024-June/033864.html is that 22u is effectively dead anyway.

**Comment by theRealAph** [comment]
> > Did you submit a jdk22 backport request?
> 
> This issue is fixed in 22 originally, so no JDK 22u backport is needed.

OK.

> Aside: my read of https://mail.openjdk.org/pipermail/jdk-updates-dev/2024-June/033864.html is that 22u is effectively dead anyway.

Ah, right. I didn't see that.

This is a pretty minor performance tweak, so it's marginal whether it should be back ported. I'm not sure the churn is justified.

**Comment by shipilev** [comment]
> This is a pretty minor performance tweak, so it's marginal whether it should be back ported. 

True. That said, lots of these papercut issues enjoy massive multipliers with our large fleets, so we prefer to patch up these minor inefficiencies as we go. :)

**Comment by pengxiaolong** [comment]
Thanks @theRealAph and @shipilev for the review and discussion. We have very large AArch64 fleet in our prod, which magnifies the minor performance improvements.

**Comment by pengxiaolong** [comment]
/approval request Backport to jdk21 to improve performance on AArch64, I have verified the the code by running all the tests, few failures not related to this build(details in PR); Applies cleanly. Risk should be low, JDK-8320379 was merged over 6 months ago w/o known issue/bug so far.

**Comment by theRealAph** [comment]
> Thanks @theRealAph and @shipilev for the review and discussion. We have very large AArch64 fleet in our prod, which magnifies the minor performance improvements.

I understand that, but wouldn't that apply to all minor performance improvements? And wouldn't the direct consequence of following that principle to its conclusion be that if anyone wanted a stable release, too bad: there isn't a stable release? I totally get why this low-risk fix is a good thing, but...

**Comment by theRealAph** [comment]
> In other words, on this trivial workload, this saves us ~0.15% of code cache. If this holds for larger apps, this amounts at about 192K for 128M code cache. This looks like a benefit enough for the cost of this backport :) It would, of course, impact even higher when we miss `ldp` optimization somewhere near heavy spills on a hot path.

So this is the kind of argument that should have been made.

It's not quite obvious that it'll help a hot path, though. ARMv8.4 made a change that makes LDP and STP atomic in some cases (see "Changes to single-copy atomicity in Armv8.4"). While this is very useful, it is a behavioural change. I'm guessing that there won't be any regressions for spills and fills, because stack-local accesses are uncontended.

**Comment by shipilev** [comment]
> > In other words, on this trivial workload, this saves us ~0.15% of code cache. If this holds for larger apps, this amounts at about 192K for 128M code cache. This looks like a benefit enough for the cost of this backport :) It would, of course, impact even higher when we miss `ldp` optimization somewhere near heavy spills on a hot path.
> 
> So this is the kind of argument that should have been made.

True. Are you satisfied with it?

> It's not quite obvious that it'll help a hot path, though. ARMv8.4 made a change that makes LDP and STP atomic in some cases (see "Changes to single-copy atomicity in Armv8.4"). While this is very useful, it is a behavioural change. I'm guessing that there won't be any regressions for spills and fills, because stack-local accesses are uncontended.

Yup. I expect that if LDP/STP merging becomes problematic on some platforms, the merging code would somehow account for that. This seems orthogonal to what this patch is doing.

**Comment by theRealAph** [comment]
> > > In other words, on this trivial workload, this saves us ~0.15% of code cache. If this holds for larger apps, this amounts at about 192K for 128M code cache. This looks like a benefit enough for the cost of this backport :) It would, of course, impact even higher when we miss `ldp` optimization somewhere near heavy spills on a hot path.
> > 
> > So this is the kind of argument that should have been made.
> 
> True. Are you satisfied with it?

Yes, I think so. It's remarkably effective for such a simple optimization.

**Review by theRealAph — APPROVED** [review]

**Comment by pengxiaolong** [comment]
Thank you @theRealAph and @shipilev for the discussion/argument, it is a good learning!

**Pull request closed without merging**
