### PR TITLE
8312049: runtime/logging/ClassLoadUnloadTest can be improved

### PR DESCRIPTION
**Pull request by cost0much**
Backport of [JDK-8312049](https://bugs.openjdk.org/browse/JDK-8312049): improving ClassLoadUnloadTest. Original commit does not apply cleanly due to this [backport](https://bugs.openjdk.org/browse/JDK-8323123) that renames createJavaProcessBuilder to createLimitedTestJavaProcessBuilder. Additionally, the options "-Xlog:class+load+cause" "-Xlog:class+load+cause+native" were not added until a later [version](https://bugs.openjdk.org/browse/JDK-8193513), thus these cases are excluded.

Passes tier1 tests on Linux x86 and MacOS aarch64, and most importantly, the test itself.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8312049](https://bugs.openjdk.org/browse/JDK-8312049) needs maintainer approval

### Issue
 * [JDK-8312049](https://bugs.openjdk.org/browse/JDK-8312049): runtime/logging/ClassLoadUnloadTest can be improved (**Enhancement** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/909/head:pull/909` \
`$ git checkout pull/909`

Update a local copy of the PR: \
`$ git checkout pull/909` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/909/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 909`

View PR using the GUI difftool: \
`$ git pr show -t 909`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/909.diff">https://git.openjdk.org/jdk21u-dev/pull/909.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/909#issuecomment-2278849052)

### CODE REVIEW

**Comment by cost0much** [comment]
/approval request Improves the test added by JDK-8312049 in JDK22. Does not apply cleanly, but the manual resolutions are trivial and have been investigated. Affected test passes. Risk is low: the change is test code only.

**Review by phohensee — APPROVED** [review]
Please tag the JBS issue after you get a review (or if the backport is clean), rather than before. :)

**Comment by jerboaa** [comment]
@cost0much Please enable GHA on your fork, thanks!

**Comment by shipilev** [comment]
> @cost0much Please enable GHA on your fork, thanks!

+1. It would be good to make sure GHA are passing before we integrate. You can trigger the GHA workflow on your branch from https://github.com/cost0much/jdk21u-dev/actions, without pushing anything to PR.

**Pull request closed without merging**
