### PR TITLE
8336284: Test TestClhsdbJstackLock.java/TestJhsdbJstackLock.java fails with -Xcomp after JDK-8335743

### PR DESCRIPTION
**Pull request by tkiriyama**
Hi all,
This pull request is the backport of JDK-8336284 .
It is clean. This change resolves a test failure introduced by JDK-8335743.
JDK-8335743 will be backported in https://github.com/openjdk/jdk21u-dev/pull/853.
I verified that TestClhsdbJstackLock.java and TestJhsdbJstackLock.java are passed with -Xcomp.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8336284](https://bugs.openjdk.org/browse/JDK-8336284) needs maintainer approval

### Issue
 * [JDK-8336284](https://bugs.openjdk.org/browse/JDK-8336284): Test TestClhsdbJstackLock.java/TestJhsdbJstackLock.java fails with -Xcomp after JDK-8335743 (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/854/head:pull/854` \
`$ git checkout pull/854`

Update a local copy of the PR: \
`$ git checkout pull/854` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/854/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 854`

View PR using the GUI difftool: \
`$ git pr show -t 854`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/854.diff">https://git.openjdk.org/jdk21u-dev/pull/854.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/854#issuecomment-2238732425)

### CODE REVIEW

**Comment by tkiriyama** [comment]
/approval request This is a JDK-8336284 backport that fixes the test issue introduced by JDK-8335743. The risk is low because this is a clean and changes tests only. I expect it to be integrated after JDK-8335743. (https://github.com/openjdk/jdk21u-dev/pull/853)

**Review by phohensee — CHANGES_REQUESTED** [review]
This PR contains code from the backport of JDK-8335743, which latter has been merged. Please remerge this PR.

**Comment by tkiriyama** [comment]
@phohensee 
Sorry, I remerged the latest changes from the master branch into this PR.
Would you sponsor it, please?

**Pull request closed without merging**
