### PR TITLE
8319970: AArch64: enable tests compiler/intrinsics/Test(Long|Integer)UnsignedDivMod.java on aarch64

### PR DESCRIPTION
**Pull request by cost0much**
Backport of [JDK-8319970](https://bugs.openjdk.org/browse/JDK-8319970) that enables tests for compiler/intrinsics/Test(Long|Integer)UnsignedDivMod.java on aarch64. Not clean because [RISC-V intrinsics for divideUnsigned and remainderUnsigned were added in JDK22](https://github.com/openjdk/jdk/commit/40a3c35aa5614be4505013d4e92ddb1b556a3622); aarch64 intrinsics for divideUnsigned and remainderUnsigned confirmed to be [released in JDK20](https://bugs.openjdk.org/browse/JDK-8287926).

This includes backport of [JDK-8319960](https://bugs.openjdk.org/browse/JDK-8319960) because the `UDivModI` or `UDivModL` nodes are supplied from x86_64.ad, thus these node checks are intended for x64 platforms. Although originally intended to fix the test failing for RISC-V intrinsics, without this exclusion the test will also fail for aarch64 platforms, thus it is included as part of the backport.

Passes affected tests on Linux aarch64 and Mac aarch64.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8319960](https://bugs.openjdk.org/browse/JDK-8319960) needs maintainer approval
- [x] [JDK-8319970](https://bugs.openjdk.org/browse/JDK-8319970) needs maintainer approval

### Issues
 * [JDK-8319970](https://bugs.openjdk.org/browse/JDK-8319970): AArch64: enable tests compiler/intrinsics/Test(Long|Integer)UnsignedDivMod.java on aarch64 (**Enhancement** - P4 - Approved)
 * [JDK-8319960](https://bugs.openjdk.org/browse/JDK-8319960): RISC-V: compiler/intrinsics/TestInteger/LongUnsignedDivMod.java failed with "counts: Graph contains wrong number of nodes" (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/914/head:pull/914` \
`$ git checkout pull/914`

Update a local copy of the PR: \
`$ git checkout pull/914` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/914/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 914`

View PR using the GUI difftool: \
`$ git pr show -t 914`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/914.diff">https://git.openjdk.org/jdk21u-dev/pull/914.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/914#issuecomment-2313500250)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by cost0much** [comment]
/approval 8319970 request Improves coverage for aarch64 platforms for compiler/intrinsics/Test(Long|Integer)UnsignedDivMod. Does not apply cleanly due to RISC-V intrinsics support only in later versions. Affected tests pass. Risk is low: the change is test code only.

/approval 8319960 request Fixes compiler/intrinsics/Test(Long|Integer)UnsignedDivMod failing when enabled for non-x64 platforms. Applies cleanly and affected tests pass. Risk is low: the change is test code only.

**Pull request closed without merging**
