### PR TITLE
8342188: Update tests to use stronger key parameters and certificates

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 21.0.6-oracle.

Locally a clean patch, but /backport did not work. 
lib files included in tests.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8342188](https://bugs.openjdk.org/browse/JDK-8342188) needs maintainer approval

### Issue
 * [JDK-8342188](https://bugs.openjdk.org/browse/JDK-8342188): Update tests to use stronger key parameters and certificates (**Sub-task** - P2 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1145/head:pull/1145` \
`$ git checkout pull/1145`

Update a local copy of the PR: \
`$ git checkout pull/1145` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1145/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1145`

View PR using the GUI difftool: \
`$ git pr show -t 1145`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1145.diff">https://git.openjdk.org/jdk21u-dev/pull/1145.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1145#issuecomment-2467950819)
</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
GHA failure: infra issue, unrelated
xcode-select: error: invalid developer directory '/Applications/Xcode_14.3.1.app/Contents/Developer'

**Comment by GoeLin** [comment]
Sorry for the force-push, but I had spoiled the merge.  Anyways, it's clean, so a single commit is the obvious thing.

**Comment by TheRealMDoerr** [comment]
It's still clean. I think we can live with force-push for clean backports :-)

**Comment by GoeLin** [comment]
GHA failure: infra issue, unrelated
error: invalid developer directory '/Applications/Xcode_14.3.1.app/Contents/Developer'

**Pull request closed without merging**
