### PR TITLE
8315923: pretouch_memory by atomic-add-0 fragments huge pages unexpectedly

### PR DESCRIPTION
**Pull request by limingliu-ampere**
This pull request ports JDK-8315923 back to JDK-21, as JDK-21 still uses atomic-add-0 to pretouch memory and results fragmented huge pages. This backport has the following differences from its original version:

- TestTransparentHugePageUsage.java gets deleted as it was deleted in JDK-8324776;
- nullptr is adopted in pretouch_thp_and_use_concurrent, as it is a part of  JDK-8327171;
- JDK-8324781 is included, as JDK-8324781 only makes changes to testcases.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8324781](https://bugs.openjdk.org/browse/JDK-8324781) needs maintainer approval
- [x] [JDK-8315923](https://bugs.openjdk.org/browse/JDK-8315923) needs maintainer approval
- [x] [JDK-8325218](https://bugs.openjdk.org/browse/JDK-8325218) needs maintainer approval

### Issues
 * [JDK-8315923](https://bugs.openjdk.org/browse/JDK-8315923): pretouch_memory by atomic-add-0 fragments huge pages unexpectedly (**Bug** - P4 - Approved)
 * [JDK-8324781](https://bugs.openjdk.org/browse/JDK-8324781): runtime/Thread/TestAlwaysPreTouchStacks.java failed with Expected a higher ratio between stack committed and reserved (**Bug** - P2 - Approved)
 * [JDK-8325218](https://bugs.openjdk.org/browse/JDK-8325218): gc/parallel/TestAlwaysPreTouchBehavior.java fails (**Bug** - P3 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/825/head:pull/825` \
`$ git checkout pull/825`

Update a local copy of the PR: \
`$ git checkout pull/825` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/825/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 825`

View PR using the GUI difftool: \
`$ git pr show -t 825`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/825.diff">https://git.openjdk.org/jdk21u-dev/pull/825.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/825#issuecomment-2210487427)

### CODE REVIEW

**Review by shipilev — CHANGES_REQUESTED** [review]
I have questions:

1. If [JDK-8324781](https://bugs.openjdk.org/browse/JDK-8324781) is included, you need to say `/issue add JDK-8324781`, and later request approval for it as well.
2. Looking at issue links, what about [JDK-8325218](https://bugs.openjdk.org/browse/JDK-8325218)?

**Comment by limingliu-ampere** [comment]
Hi @shipilev! Thank you for your suggestions. The root case of JDK-8324781 and JDK-8325218 are the same, so they were solved in the same commit. I added them altogether.

**Review by shipilev — APPROVED** [review]
All right, this makes sense, thanks!

**Pull request closed without merging**
