### PR TITLE
8333542: Breakpoint in parallel code does not work

### PR DESCRIPTION
**Pull request by MBaesken**
Backport of 
8333542

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8333542](https://bugs.openjdk.org/browse/JDK-8333542) needs maintainer approval

### Issue
 * [JDK-8333542](https://bugs.openjdk.org/browse/JDK-8333542): Breakpoint in parallel code does not work (**Bug** - P3 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/823/head:pull/823` \
`$ git checkout pull/823`

Update a local copy of the PR: \
`$ git checkout pull/823` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/823/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 823`

View PR using the GUI difftool: \
`$ git pr show -t 823`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/823.diff">https://git.openjdk.org/jdk21u-dev/pull/823.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/823#issuecomment-2209120476)

### CODE REVIEW

**Comment by MBaesken** [comment]
src/hotspot/share/classfile/vmSymbols.hpp
int_array_signature is already in 21u-dev so no change to this file - we have 1 file less in this PR compared to head
Some other files have diffs in the strides and minor diff.

cpCache.cpp
has different coding in set_method_handle_common

**Review by RealLucy — APPROVED** [review]
Looks good.

**Comment by plummercj** [comment]
Make sure [JDK-8335134](https://bugs.openjdk.org/browse/JDK-8335134) also gets backported after this backport is complete.

**Comment by MBaesken** [comment]
> Make sure [JDK-8335134](https://bugs.openjdk.org/browse/JDK-8335134) also gets backported after this backport is complete.

Thanks for the hint, it is already labeled sap-interest1 , so planned to be backported.

**Review by RealLucy — APPROVED** [review]
Still looking good.
Thanks for removing the TODO.

**Pull request closed without merging**
