### PR TITLE
8321894: Bump update version for OpenJDK: 21.0.3

### PR DESCRIPTION
**Pull request by jerboaa**
Required version bump to get `21.0.3` development going.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8321894](https://bugs.openjdk.org/browse/JDK-8321894) needs maintainer approval

### Issue
 * [JDK-8321894](https://bugs.openjdk.org/browse/JDK-8321894): Bump update version for OpenJDK: 21.0.3 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/13/head:pull/13` \
`$ git checkout pull/13`

Update a local copy of the PR: \
`$ git checkout pull/13` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/13/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 13`

View PR using the GUI difftool: \
`$ git pr show -t 13`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/13.diff">https://git.openjdk.org/jdk21u-dev/pull/13.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/13#issuecomment-1853723123)

### CODE REVIEW

**Review by GoeLin — COMMENTED** [review]
LGTM

**Comment by jerboaa** [comment]
> LGTM

Do you mind approving it? I'd like to test the PR workflow.

**Review by GoeLin — APPROVED** [review]

**Comment by GoeLin** [comment]
I meant to ... sorry :) Now it might work!

**Comment by jerboaa** [comment]
Does anyone know why skara doesn't resolve the bug in JBS? Is it just slow? @kevinrushforth would you know?

**Comment by kevinrushforth** [comment]
It should be configured to update JBS and resolve the issue, so I would guess that it is just slow.

@erikj79 can you comment?

**Comment by kevinrushforth** [comment]
It was a misconfiguration on our end. The JBS bug has been resolved.

**Comment by jerboaa** [comment]
> It was a misconfiguration on our end. The JBS bug has been resolved.

OK. Thanks for following up on this!

**Pull request closed without merging**
