### PR TITLE
8341927: Replace hardcoded security providers with new test.provider.name system property

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 21.0.6-oracle.

I resolved two files:
test/jdk/sun/security/mscapi/InteropWithSunRsaSign.java
Copyright

test/jdk/sun/security/pkcs11/Signature/SigInteropPSS2.java
Resolved because 8325164: Named groups and signature schemes unavailable with SunPKCS11 in FIPS mode not in 21.

Tests all pass except for three I skipped:
test/jdk/sun/security/pkcs11/rsa/GenKeyStore.java
test/jdk/sun/security/rsa/GenKeyStore.java
test/jdk/javax/crypto/SecretKeyFactory/evilprov/com/evilprovider/EvilHmacSHA1.java
Checked the change in these files.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8343848](https://bugs.openjdk.org/browse/JDK-8343848) needs maintainer approval
- [x] [JDK-8341927](https://bugs.openjdk.org/browse/JDK-8341927) needs maintainer approval

### Issues
 * [JDK-8341927](https://bugs.openjdk.org/browse/JDK-8341927): Replace hardcoded security providers with new test.provider.name system property (**Enhancement** - P2 - Approved)
 * [JDK-8343848](https://bugs.openjdk.org/browse/JDK-8343848): Fix typo of property name in TestOAEPPadding after 8341927 (**Bug** - P5 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1138/head:pull/1138` \
`$ git checkout pull/1138`

Update a local copy of the PR: \
`$ git checkout pull/1138` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1138/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1138`

View PR using the GUI difftool: \
`$ git pr show -t 1138`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1138.diff">https://git.openjdk.org/jdk21u-dev/pull/1138.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1138#issuecomment-2462209813)
</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
GHA failure: various infra issues. Unrelated.
Will try to restart subtests anyways, as this is a large change.

**Review by RealLucy — CHANGES_REQUESTED** [review]
Looks almost good to me.

Found one inconsistency (or typo?) in 
test/jdk/com/sun/crypto/provider/Cipher/RSA/TestOAEPPadding.java
It is also present in JDK head revision. 
Not sure if it should be corrected here or fixed with a follow-up PR in head (and subsequent backport).

**Comment by GoeLin** [comment]
Nice finding! I think it should be fixed in head. I will double check and open an issue in head and bring that to 21 later on.
But the test works anyways, as the default string is used if the propery is empty.

**Comment by RealLucy** [comment]
Yes, this typo will only be noticed if the test is executed with a non-default provider.

I will approve this PR.

**Review by RealLucy — APPROVED** [review]
Typo cleanup delegated to a follow-up fix in head.

**Comment by GoeLin** [comment]
\issue 8343848

Including this fix Lutz spotted in his review. Better to have this correct right away, and simplifies backport to 17.

**Review by RealLucy — APPROVED** [review]
Looks good now.

**Comment by GoeLin** [comment]
GHA failure: infra issue, unrelated
error: invalid developer directory '/Applications/Xcode_14.3.1.app/Contents/Developer'

**Pull request closed without merging**
