### PR TITLE
8333887: ubsan: unsafe.cpp:247:13: runtime error: store to null pointer of type 'volatile int'

### PR DESCRIPTION
**Pull request by luwang1103**
hi @shipilev ,

This pull request contains a backport of commit [0d3a3771](https://git.openjdk.org/jdk/commit/0d3a3771c3777d3dd1fec8dc8faed5fd02b06830) from the [master](https://github.com/openjdk/jdk) repository.

The commit being backported was authored by Matthias Baesken on 13 Jun 2024.

Thanks！

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8333887](https://bugs.openjdk.org/browse/JDK-8333887) needs maintainer approval

### Issue
 * [JDK-8333887](https://bugs.openjdk.org/browse/JDK-8333887): ubsan: unsafe.cpp:247:13: runtime error: store to null pointer of type 'volatile int' (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/837/head:pull/837` \
`$ git checkout pull/837`

Update a local copy of the PR: \
`$ git checkout pull/837` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/837/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 837`

View PR using the GUI difftool: \
`$ git pr show -t 837`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/837.diff">https://git.openjdk.org/jdk21u-dev/pull/837.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/837#issuecomment-2224259230)

### CODE REVIEW

**Comment by shipilev** [comment]
Why is this not clean? The indenting is not the same as in original patch?

**Comment by luwang1103** [comment]
> Hm, where is copyright header update comes from? This is confusing...
> 
> To be extra clear, this PR should be exactly like the upstream change: [openjdk/jdk@0d3a377](https://github.com/openjdk/jdk/commit/0d3a3771c3777d3dd1fec8dc8faed5fd02b06830), unless there is a good reason to deviate. The indentation is still not fixed, AFAICS. How do you do the backports? Picking up and applying the full changsets, or making the patch by hand?

In the [master](https://github.com/openjdk/jdk) repository, there are other modifications to [unsafe.cpp](https://github.com/openjdk/jdk/commits/master/src/hotspot/share/prims/unsafe.cpp ).  Other modifications do not belong to this bug. What should I do next? This is my first time submitting code, and there are many areas that I am currently studying. Thank you for your guidance.

**Comment by shipilev** [comment]
> Other modifications do not belong to this bug. What should I do next? 

Right, so indenting for surrounding code had changed a bit. This is fine, we can make this one into unclean backport. 

To proceed, I think you need to: 
 1. Drop the copyright year change from this PR.
 2. Match the indenting of the original changeset: `#if` block should start a column 0.

**Comment by shipilev** [comment]
Spot the difference, this is original change:

```
  // we use this method at some places for writing to 0 e.g. to cause a crash;
  // ubsan does not know that this is the desired behavior
#if defined(__clang__) || defined(__GNUC__)
__attribute__((no_sanitize("undefined")))
#endif
```

Current PR misses two spaces before `//` comments:

```
// we use this method at some places for writing to 0 e.g. to cause a crash;
// ubsan does not know that this is the desired behavior
#if defined(__clang__) || defined(__GNUC__)
__attribute__((no_sanitize("undefined")))
#endif
```

This might sound like odd thing to get right, but matching the indenting _exactly_ would make your follow-up backport in the same place clean. Make sure you have the new hunks _exactly_ the same.

**Comment by luwang1103** [comment]
/approval request The code applies cleanly. Low risk: It is a corner case which is not triggered by the current code. In order to avoid bugs in the future, it is good to backport it.

**Pull request closed without merging**
