### PR TITLE
8318757: VM_ThreadDump asserts in interleaved ObjectMonitor::deflate_monitor calls

### PR DESCRIPTION
**Pull request by shipilev**
This resolves potentially catastrophic bug in monitor deflation. Thread dumps are routinely requested by profilers, so it is a real in-production risk. It would be more prominent as we backport improvements in monitor deflation code like [JDK-8319048](https://bugs.openjdk.org/browse/JDK-8319048). The interaction between deflation thread that can be stopped at safepoint in the middle of deflation and the VM op that deflates monitors itself may corrupt the VM state.

This series of backports moves all deflation to monitor deflation thread, avoiding the issue. There are 4 interconnected issues, which are backported here atomically:

- **[JDK-8318757](https://bugs.openjdk.org/browse/JDK-8318757): VM_ThreadDump asserts in interleaved ObjectMonitor::deflate_monitor calls.** The core part, deferring deflation to monitor deflation thread. The new test needs `-XX:+UnlockExperimentalVMOptions` to gain access to `-XX:LockingMode`. Otherwise applies cleanly. It needs JDK-8320515 as the followup.
- **[JDK-8319896](https://bugs.openjdk.org/browse/JDK-8319896): Remove monitor deflation from final audit.** Removes the remaining part that might call into deflation outside of monitor deflation thread. Applies cleanly. Makes JDK-8320515 backport clean. It needs JDK-8325437 as the followup.
- **[JDK-8320515](https://bugs.openjdk.org/browse/JDK-8320515): assert(monitor-&gt;object_peek() != nullptr) failed**. Owned monitors should not have a dead object. Follow-up for JDK-8318757, fixes the JNI interaction problem. Does not apply cleanly due to minor conflict in `JtregNativeHotspot.gmk`.
- **[JDK-8325437](https://bugs.openjdk.org/browse/JDK-8325437): Safepoint polling in monitor deflation can cause massive logs.** Followup for JDK-8319896, reducing the logs noise.

@stefank -- it looks like you are tasked with backporting some of this to 21.0.4-oracle. Maybe you want to review this PR, which would also allow you to pick it up as commit later? :)

Additional testing:
 - [x] Linux x86_64 server fastdebug, `all` tests pass

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8318757](https://bugs.openjdk.org/browse/JDK-8318757) needs maintainer approval
- [x] [JDK-8319896](https://bugs.openjdk.org/browse/JDK-8319896) needs maintainer approval
- [x] [JDK-8320515](https://bugs.openjdk.org/browse/JDK-8320515) needs maintainer approval
- [x] [JDK-8325437](https://bugs.openjdk.org/browse/JDK-8325437) needs maintainer approval

### Issues
 * [JDK-8318757](https://bugs.openjdk.org/browse/JDK-8318757): VM_ThreadDump asserts in interleaved ObjectMonitor::deflate_monitor calls (**Bug** - P2 - Approved)
 * [JDK-8319896](https://bugs.openjdk.org/browse/JDK-8319896): Remove monitor deflation from final audit (**Enhancement** - P4 - Approved)
 * [JDK-8320515](https://bugs.openjdk.org/browse/JDK-8320515): assert(monitor-&gt;object_peek() != nullptr) failed: Owned monitors should not have a dead object (**Bug** - P3 - Approved)
 * [JDK-8325437](https://bugs.openjdk.org/browse/JDK-8325437): Safepoint polling in monitor deflation can cause massive logs (**Enhancement** - P4 - Approved)

### Reviewers
 * [Stefan Karlsson](https://openjdk.org/census#stefank) (@stefank - **Reviewer**)
 * [Andrew Dinn](https://openjdk.org/census#adinn) (@adinn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/337/head:pull/337` \
`$ git checkout pull/337`

Update a local copy of the PR: \
`$ git checkout pull/337` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/337/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 337`

View PR using the GUI difftool: \
`$ git pr show -t 337`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/337.diff">https://git.openjdk.org/jdk21u-dev/pull/337.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/337#issuecomment-1983186200)

### CODE REVIEW

**Comment by shipilev** [comment]
GHA RISC-V failure is known environmental issue.

**Review by stefank — APPROVED** [review]
> @stefank -- it looks like you are tasked with backporting some of this to 21.0.4-oracle. Maybe you want to review this PR, which would also allow you to pick it up as commit later? :)

Yes, these are essentially the same patches that I've been testing for 21.0.4-oracle.

**Comment by shipilev** [comment]
> > @stefank -- it looks like you are tasked with backporting some of this to 21.0.4-oracle. Maybe you want to review this PR, which would also allow you to pick it up as commit later? :)
> 
> Yes, these are essentially the same patches that I've been testing for 21.0.4-oracle.

OK, great, thanks for looking.

**Comment by shipilev** [comment]
/approval 8318757 request This resolves potentially catastrophic bug in monitor deflation due to interleaving with thread dumping code that is frequently exercised by profilers. This is a part of atomic 21u integration, see 21u-dev PR for more details. Applies cleanly, but the new test needs -XX:+UnlockExperimentalVMOptions to gain access to -XX:LockingMode. After that amendment, all tests pass. Was in mainline for several months. Small bugtail: needs JDK-8320515 as the followup. 

/approval 8319896 request This resolves the last place that might lead to bugs due to interleaving with concurrent monitor deflation. Less important than JDK-8318757, since this only happens on JVM shutdown, but it makes relevant backports like JDK-8320515 clean. This is a part of atomic 21u integration, see 21u-dev PR for more details. Applies cleanly. All tests pass. Was in mainline for several months. Small bugtail: needs JDK-8325437 as the followup.

/approval 8320515 request Fixes the JNI interaction problem, followup for JDK-8318757. This is a part of atomic 21u integration, see 21u-dev PR for more details. Does not apply cleanly due to minor conflict in JtregNativeHotspot.gmk. All tests pass. Was in mainline for several months, without bugtail.

/approval 8325437 request Reduces the logs noise, followup for JDK-8319896. This is a part of atomic 21u integration, see 21u-dev PR for more details. Applies cleanly. All tests pass. Was in mainline for a month, without bugtail.

**Comment by jerboaa** [comment]
@adinn Could you please review this as well? Thanks.

**Comment by adinn** [comment]
@jerboaa Sure, I'll take a look.

**Review by adinn — COMMENTED** [review]
Backport looks good. The only thing to note is that we might want to follow this up with whatever is done to resolve [JDK-8320720](https://bugs.openjdk.org/browse/JDK-8320720).

**Review by adinn — APPROVED** [review]

**Comment by jerboaa** [comment]
Thanks!

**Comment by shipilev** [comment]
Thanks all!

/integrate

**Pull request closed without merging**
