### PR TITLE
8344275: tools/jpackage/windows/Win8301247Test.java fails on localized Windows platform

### PR DESCRIPTION
**Pull request by kurashige23**
Hi all,

This is a backport of JDK-8344275 : tools/jpackage/windows/Win8301247Test.java fails on localized Windows platform

Original patch does not apply cleanly because JDK-8340311 and JDK-8343314 are not applied to jdk21.
JDK-8340311 and JDK-8343314 are enhancement, so I don't backport them.

Testing: tools/jpackage tests importing jdk.jpackage.test.Executor on Windows Server 2019 (Japanese and English locales)

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8344275](https://bugs.openjdk.org/browse/JDK-8344275) needs maintainer approval

### Issue
 * [JDK-8344275](https://bugs.openjdk.org/browse/JDK-8344275): tools/jpackage/windows/Win8301247Test.java fails on localized Windows platform (**Bug** - P4 - Approved)

### Reviewers
 * [Alexey Semenyuk](https://openjdk.org/census#asemenyuk) (@alexeysemenyukoracle - Author)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1182/head:pull/1182` \
`$ git checkout pull/1182`

Update a local copy of the PR: \
`$ git checkout pull/1182` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1182/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1182`

View PR using the GUI difftool: \
`$ git pr show -t 1182`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1182.diff">https://git.openjdk.org/jdk21u-dev/pull/1182.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1182#issuecomment-2500799840)
</details>

### CODE REVIEW

**Comment by kurashige23** [comment]
Could anyone review this backport please?

**Review by phohensee — APPROVED** [review]

**Comment by kurashige23** [comment]
/approval request Backporting this patch resolves tools/jpackage/windows/Win8301247Test.java failure.
Original patch does not apply cleanly because JDK-8340311 and JDK-8343314 are not applied to jdk21.
Test-only fix, low risk.
tools/jpackage tests importing jdk.jpackage.test.Executor on Windows Server 2019 (Japanese and English locales) pass.

**Comment by GoeLin** [comment]
Hi, I am currently backporting 8343314, will approve after pushing that.

**Pull request closed without merging**
