### PR TITLE
8310308: IR Framework: check for type and size of vector nodes

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this to improve testing of C2 in 22u. It will simplify backporting tests of fixes to C2, as, e.g. " 8313720: C2 SuperWord: wrong result with -XX:+UseVectorCmov -XX:+UseCMoveUnconditionally"

I had to trivially resolve three files:

test/hotspot/jtreg/compiler/loopopts/superword/TestDependencyOffsets.java
Resolved the bugid in comment.

patching file test/hotspot/jtreg/compiler/vectorization/runner/BasicDoubleOpTest.java
patching file test/hotspot/jtreg/compiler/vectorization/runner/BasicFloatOpTest.java
These had to be resolved because "8308340: C2: Idealize Fma nodes" is not in 21. Trivial.
That change is huge thus not a candidate for backport.

Further I include "8314513: [IR Framework] Some internal IR Framework tests are failing after JDK-8310308 on PPC and Cascade Lake".  This is a follow-up fix of the tests.

All tests passed locally. 

It's a test-only change.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8314513](https://bugs.openjdk.org/browse/JDK-8314513) needs maintainer approval
- [x] [JDK-8310308](https://bugs.openjdk.org/browse/JDK-8310308) needs maintainer approval

### Issues
 * [JDK-8310308](https://bugs.openjdk.org/browse/JDK-8310308): IR Framework: check for type and size of vector nodes (**Enhancement** - P4 - Approved)
 * [JDK-8314513](https://bugs.openjdk.org/browse/JDK-8314513): [IR Framework] Some internal IR Framework tests are failing after JDK-8310308 on PPC and Cascade Lake (**Bug** - P4 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/29/head:pull/29` \
`$ git checkout pull/29`

Update a local copy of the PR: \
`$ git checkout pull/29` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/29/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 29`

View PR using the GUI difftool: \
`$ git pr show -t 29`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/29.diff">https://git.openjdk.org/jdk21u-dev/pull/29.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/29#issuecomment-1855936943)

### CODE REVIEW

**Comment by GoeLin** [comment]
Pre-submit: compiler/c2/irTests/TestVectorizationMismatchedAccess failed.

**Comment by GoeLin** [comment]
TestVectorizationMismatchedAccess.java was failing.
This is because in head, subtest testByteByte2 was enabled by 8310308. But in 21, it is disabled. 
If I enable it in 21 without this change, it fails with the same message as with the change. So I disabled it again.

As I understand, 21 does not generate vector nodes for the test method, and in 22 there was a functional improvement.

**Review by MBaesken — APPROVED** [review]

**Pull request closed without merging**
