### PR TITLE
8312194: test/hotspot/jtreg/applications/ctw/modules/jdk_crypto_ec.java cannot handle empty modules

### PR DESCRIPTION
**Pull request by luchenlin**
I backport this for parity with 21.0.3-oracle.
‘applications/ctw/modules/jdk_crypto_ec.java 8312194 generic-all’ not in test/hotspot/jtreg/ProblemList.txt,
so make it clean

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8312194](https://bugs.openjdk.org/browse/JDK-8312194) needs maintainer approval

### Issue
 * [JDK-8312194](https://bugs.openjdk.org/browse/JDK-8312194): test/hotspot/jtreg/applications/ctw/modules/jdk_crypto_ec.java cannot handle empty modules (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/590/head:pull/590` \
`$ git checkout pull/590`

Update a local copy of the PR: \
`$ git checkout pull/590` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/590/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 590`

View PR using the GUI difftool: \
`$ git pr show -t 590`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/590.diff">https://git.openjdk.org/jdk21u-dev/pull/590.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/590#issuecomment-2121870817)

### CODE REVIEW

**Comment by RealCLanger** [comment]
Hm, I'm not sure if backporting this makes sense since the jdk.crypto.ec module was emptied only in JDK22...

**Comment by TheRealMDoerr** [comment]
I don't know why Oracle has backported it, but I'd prefer to follow. Does keeping it have any advantage?

**Comment by RealCLanger** [comment]
OK but then let's just backport it to the releases where Oracle has it as well.

**Pull request closed without merging**
