### PR TITLE
8310513: [s390x] Intrinsify recursive ObjectMonitor locking

### PR DESCRIPTION
**Pull request by offamitkumar**
Hi all,

This pull request contains a backport of commit [47df1459](https://github.com/openjdk/jdk/commit/47df14590c003ccb1607ec0edfe999fcf2aebd86) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Amit Kumar on 10 Apr 2024 and was reviewed by Lutz Schmidt and Martin Doerr.

Thanks!

Benchmarking: 
```
./build/linux-s390x-server-release/jdk/bin/java -Xms4g -Xmx4g -jar dacapo-9.12-MR1-bach.jar h2 -s huge -t 1 -n 1

Without the patch:

===== DaCapo 9.12-MR1 h2 PASSED in 209768 msec ===== 
===== DaCapo 9.12-MR1 h2 PASSED in 197472 msec =====
===== DaCapo 9.12-MR1 h2 PASSED in 222872 msec =====
===== DaCapo 9.12-MR1 h2 PASSED in 215725 msec =====


with patch: 
===== DaCapo 9.12-MR1 h2 PASSED in 171055 msec =====
===== DaCapo 9.12-MR1 h2 PASSED in 169696 msec =====
===== DaCapo 9.12-MR1 h2 PASSED in 174032 msec =====
===== DaCapo 9.12-MR1 h2 PASSED in 167271 msec =====
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8310513](https://bugs.openjdk.org/browse/JDK-8310513) needs maintainer approval

### Issue
 * [JDK-8310513](https://bugs.openjdk.org/browse/JDK-8310513): [s390x] Intrinsify recursive ObjectMonitor locking (**Enhancement** - P4 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**) ⚠️ Review applies to [50b25633](https://git.openjdk.org/jdk21u-dev/pull/537/files/50b256332732c27188156ffbc71040851c4b8110)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/537/head:pull/537` \
`$ git checkout pull/537`

Update a local copy of the PR: \
`$ git checkout pull/537` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/537/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 537`

View PR using the GUI difftool: \
`$ git pr show -t 537`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/537.diff">https://git.openjdk.org/jdk21u-dev/pull/537.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/537#issuecomment-2079734826)

### CODE REVIEW

**Comment by offamitkumar** [comment]
I have done tier1 testing and no new failure appeared in JDK-21 as well. 

one of the failing test case `TestSigInfoInHsErrFile.java`  will be fixed by https://github.com/openjdk/jdk21u-dev/pull/541

**Comment by offamitkumar** [comment]
@RealLucy would you please review this backport as well. Testing & Benchmark result I have already added.

**Comment by offamitkumar** [comment]
There were conflicts in the  copyright header. 

```diff
diff --cc src/hotspot/cpu/s390/macroAssembler_s390.cpp
index 8a56f3e4c2b,fd04a66a843..00000000000
--- a/src/hotspot/cpu/s390/macroAssembler_s390.cpp
+++ b/src/hotspot/cpu/s390/macroAssembler_s390.cpp
@@@ -1,6 -1,6 +1,11 @@@
  /*
++<<<<<<< HEAD
 + * Copyright (c) 2016, 2023, Oracle and/or its affiliates. All rights reserved.
 + * Copyright (c) 2016, 2023 SAP SE. All rights reserved.
++=======
+  * Copyright (c) 2016, 2024, Oracle and/or its affiliates. All rights reserved.
+  * Copyright (c) 2016, 2024 SAP SE. All rights reserved.
++>>>>>>> 47df14590c0 (8310513: [s390x] Intrinsify recursive ObjectMonitor locking)
   * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
   *
   * This code is free software; you can redistribute it and/or modify it
```

**Comment by offamitkumar** [comment]
/approval request backport is required to JDK-21 as other archs have added this change in JDK-21, but on s390x we ported it in JDK-23.

**Comment by offamitkumar** [comment]
>you can force the state to "clean" by adding the "/clean" tag.

ohh, thanks, I didn't know that it is possible to mark PR forcefully clean.  I had missed it while looking at bot-commands.

**Comment by GoeLin** [comment]
Hi @offamitkumar, you changed the Oracle Copyright. This is not part of the original change. Please revert that and the change will be clean.

**Comment by GoeLin** [comment]
The copyright dates must be the max of the date in the 21u repo and the date in the patch backported.  No other changes to the copyright should be made.

**Comment by GoeLin** [comment]
Also, please enable the GHA tests on your repo.

**Comment by offamitkumar** [comment]
>Hi @offamitkumar, you changed the Oracle Copyright. This is not part of the original change. Please revert that and the change will be clean.

Nice, Thank you, Goetz

**Comment by offamitkumar** [comment]
Thanks @GoeLin @RealLucy for advice & review. 

/integrate

**Pull request closed without merging**
