### PR TITLE
8311893: Interactive component with ARIA role 'tabpanel' does not have a programmatically associated name

### PR DESCRIPTION
**Pull request by psoujany**
This PR is a backport of https://github.com/openjdk/jdk/pull/16148.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8311893](https://bugs.openjdk.org/browse/JDK-8311893) needs maintainer approval

### Issue
 * [JDK-8311893](https://bugs.openjdk.org/browse/JDK-8311893): Interactive component with ARIA role 'tabpanel' does not have a programmatically associated name (**Enhancement** - P4 - Approved)

### Reviewers
 * [Hannes Wallnöfer](https://openjdk.org/census#hannesw) (@hns - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/234/head:pull/234` \
`$ git checkout pull/234`

Update a local copy of the PR: \
`$ git checkout pull/234` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/234/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 234`

View PR using the GUI difftool: \
`$ git pr show -t 234`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/234.diff">https://git.openjdk.org/jdk21u-dev/pull/234.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/234#issuecomment-1926736498)

### CODE REVIEW

**Review by hns — APPROVED** [review]

**Comment by psoujany** [comment]
@hns Could you please add jdk21 tag in the OpenJDK issue. Thank you.
https://bugs.openjdk.org/browse/JDK-8311893

**Comment by GoeLin** [comment]
You are missing the fix-request comments. Please read https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix.
Removing the tags in the meantime.

**Comment by psoujany** [comment]
/approval psoujany request JDK21 generates docs with violations which got fixed in later release i.e 23. Hence requesting this backport which resolves couple of the violations. Risk would be moderate as this affects javadoc generation. No regressions shown in Tier1 and javadoc tests from jdk21u-dev.

**Comment by psoujany** [comment]
/approval request JDK21 generates docs with couple of violations which got fixed in later release i.e 23. Hence requesting this backport. No regressions shown in Tier1 and javadoc tests from jdk21u-dev.

**Comment by psoujany** [comment]
@GoeLin I've raised fix request. Thank you.

**Comment by psoujany** [comment]
@GoeLin Could you please sponsor this fix. Thank you.

**Pull request closed without merging**
