### PR TITLE
8342905: Thread.setContextClassloader from thread in FJP commonPool task no longer works after JDK-8327501 redux

### PR DESCRIPTION
**Pull request by franferrax**
Hi,

I would like to propose a [JDK-8342905](https://bugs.openjdk.org/browse/JDK-8342905 "Thread.setContextClassloader from thread in FJP commonPool task no longer works after JDK-8327501 redux") (openjdk/jdk23u@872ae1347198408ffd62559ca8c1a7420c4a8108) backport from 23u to 21u.

The backport is not clean, for the following reasons:

* The `jdk.internal.access.JavaLangAccess` import context in `ForkJoinPool.java` has changed from 21u to 23u, due to [JDK-8288899](https://bugs.openjdk.org/browse/JDK-8288899 "java/util/concurrent/ExecutorService/CloseTest.java failed with \"InterruptedException: sleep interrupted\"") (openjdk/jdk@667cca9d7aef1ff4abe630cefaac34c0b1646925)
* The `jdk.internal.access.JavaLangAccess::allowSecurityManager` method didn't exist in 21u, so I picked it from [JDK-8296244](https://bugs.openjdk.org/browse/JDK-8296244 "Alternate implementation of user-based authorization Subject APIs that doesn’t depend on Security Manager APIs") (openjdk/jdk@d32746ef4a0ce6fec558274244321991be141698)
    * We don't need [JDK-8296244](https://bugs.openjdk.org/browse/JDK-8296244 "Alternate implementation of user-based authorization Subject APIs that doesn’t depend on Security Manager APIs"), just the access to the `System::allowSecurityManager` private method
    * I don't see [JDK-8296244](https://bugs.openjdk.org/browse/JDK-8296244 "Alternate implementation of user-based authorization Subject APIs that doesn’t depend on Security Manager APIs") as a possible dependency candidate, given it is a much broader change with its own CSR affecting the Java SE API and only approved for 23

This pull request depends on @martinuy's #1181.

#### Testing

As part of our testing, we observed all the tests pass in the following categories:

* `jdk:tier1` (see [GitHub Actions run](https://github.com/franferrax/jdk21u-dev/actions/runs/12126257318))
* `jdk/java/util/concurrent/forkjoin`
* `jdk/java/util/concurrent/tck`

Additionally, an internal test for [JDK-8237117](https://bugs.openjdk.org/browse/JDK-8237117 "Better ForkJoinPool behavior") was executed without issues.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8342905](https://bugs.openjdk.org/browse/JDK-8342905) needs maintainer approval

### Issue
 * [JDK-8342905](https://bugs.openjdk.org/browse/JDK-8342905): Thread.setContextClassloader from thread in FJP commonPool task no longer works after JDK-8327501 redux (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - **Reviewer**) Review applies to [f02d74fb](https://git.openjdk.org/jdk21u-dev/pull/1192/files/f02d74fb73125f57ed1bac82474a0d9a224a35bf)
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1192/head:pull/1192` \
`$ git checkout pull/1192`

Update a local copy of the PR: \
`$ git checkout pull/1192` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1192/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1192`

View PR using the GUI difftool: \
`$ git pr show -t 1192`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1192.diff">https://git.openjdk.org/jdk21u-dev/pull/1192.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1192#issuecomment-2513026615)
</details>

### CODE REVIEW

**Review by martinuy — APPROVED** [review]
The proposed backport looks good to me. I agree with not considering JDK-8296244 a dependency.

**Review by martinuy — APPROVED** [review]
Sending the approval again, after being moved out of Draft for the Skara bot to get it.

**Comment by jerboaa** [comment]
@franferrax Please merge master since the dependency integrated. Thanks!

**Comment by franferrax** [comment]
Please note that the old PR diff exactly matches the new one:

* Old diff: f02d74fb73125f57ed1bac82474a0d9a224a35bf (previous tip of this PR branch) against its parent, 67a36bded7f03fc7aee54372e71f8016d67971fd (tip of #1181, on which this PR depended)
* New diff: 84a0ff07baa37d1a93e698f29a3c1bd6fa0bfd45 (current tip of this PR branch) against its second parent, 96a3a88ee206680ba06c6ed876b538de41ff511c (current tip of `master`)

For example the following commands:

```bash
git diff 67a36bded7f03fc7aee54372e71f8016d67971fd f02d74fb73125f57ed1bac82474a0d9a224a35bf | sha512sum
git diff 96a3a88ee206680ba06c6ed876b538de41ff511c 84a0ff07baa37d1a93e698f29a3c1bd6fa0bfd45 | sha512sum
```

Both produce the same output:

```
0a7bdece0a0182399b03b7760046a12866781c7d7e519cfa052e93da9bf65b3f9d12e389bee37e86d52cf1fa0a841f5bc8aba94e9d6524aacff441468b67f2a4  -
```

Anyway, we'll want to wait for [run 12143610533](https://github.com/franferrax/jdk21u-dev/actions/runs/12143610533) before integrating.

**Review by jerboaa — APPROVED** [review]
Looks OK to me.

**Comment by jerboaa** [comment]
> Please note that the old PR diff exactly matches the new one:

Yes, understood. But for dependent PRs it's advised to merge master once the dependent PR integrates before actually integrating since the base revision changes and the actual commit might not be right. Not a problem in this case, but still good to merge master. Thanks!

**Comment by franferrax** [comment]
> > Please note that the old PR diff exactly matches the new one:
> 
> Yes, understood. But for dependent PRs it's advised to merge master once the dependent PR integrates before actually integrating since the base revision changes and the actual commit might not be right. Not a problem in this case, but still good to merge master. Thanks!

Yes, once the Skara bot changes the base, the PR gets a conflict and the rebase or merge becomes strictly necessary.

Sorry for the confusion, I should have mentioned I was showing the same-diff evidence only to make the re-review process faster after the merge (in case @martinuy was going to re-review, and wanted to rely on his previous review by acknowledging that nothing changed).

**Comment by jerboaa** [comment]
Thanks. Please integrate once GHA is clean.

**Pull request closed without merging**
