### PR TITLE
8331771: ZGC: Remove OopMapCacheAlloc_lock ordering workaround

### PR DESCRIPTION
**Pull request by pengxiaolong**
I'd like to backport [JDK-8331771](https://bugs.openjdk.org/browse/JDK-8331771) to jdk21

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8331771](https://bugs.openjdk.org/browse/JDK-8331771) needs maintainer approval

### Issue
 * [JDK-8331771](https://bugs.openjdk.org/browse/JDK-8331771): ZGC: Remove OopMapCacheAlloc_lock ordering workaround (**Enhancement** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [3072df2a](https://git.openjdk.org/jdk21u-dev/pull/626/files/3072df2a0db82ad424d2c7c2ed8fc6242930b64c)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/626/head:pull/626` \
`$ git checkout pull/626`

Update a local copy of the PR: \
`$ git checkout pull/626` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/626/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 626`

View PR using the GUI difftool: \
`$ git pr show -t 626`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/626.diff">https://git.openjdk.org/jdk21u-dev/pull/626.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/626#issuecomment-2141314963)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by pengxiaolong** [comment]
/approval request Backport [JDK-8331771](https://bugs.openjdk.org/browse/JDK-8331771) to remove OopMapCacheAlloc_lock ordering workaround in ZGC, the blocker issue JDK-8331714 has already been backported to jdk21. Applies cleanly after merging master into backport branch; Risk should be on the lower side since change of issue is fairly simple.

**Comment by pengxiaolong** [comment]
Thanks for the review and approval!

/integrate

**Pull request closed without merging**
