### PR TITLE
8320061: [nmt] Multiple issues with peak accounting

### PR DESCRIPTION
**Pull request by Delawen**
This is a follow up of https://github.com/openjdk/jdk21u-dev/pull/440

This backport fixes several NMT things, among those, the problem with largest_committed being 0KB as shown on the previous PR.

Example of output:

```
$ jcmd 20088 VM.native_memory detail | grep "mmap: reserved="
                            (mmap: reserved=8388608KB, committed=618496KB, at peak) 
                            (mmap: reserved=1048576KB, committed=32064KB, at peak) 
                            (mmap: reserved=528392KB, committed=41416KB, at peak) 
                            (mmap: reserved=197140KB, committed=45380KB, at peak) 
                            (mmap: reserved=40KB, committed=36KB, at peak) 
                            (mmap: reserved=8KB, committed=8KB, at peak) 
                            (mmap: reserved=262144KB, committed=224640KB, at peak) 
                            (mmap: reserved=0KB, committed=0KB, peak=20KB) 
```
As described in the original PR, other features in this PR is fixing the scale so it also shows when the allocation value is zero (note the GB now instead of showing KB as before, and the *0GB* that is shown):

```
$ jcmd 20088 VM.native_memory detail scale=g | grep "committed"
Total: reserved=11GB, committed=2GB
       mmap:   reserved=10GB, committed=1GB
-                 Java Heap (reserved=8GB, committed=1GB)
                            (mmap: reserved=8GB, committed=1GB, at peak) 
-                     Class (reserved=1GB, committed=0GB)
                            (mmap: reserved=1GB, committed=0GB, at peak) 
                            (    reserved=0GB, committed=0GB)
                            (    reserved=1GB, committed=0GB)
-                      Code (reserved=1GB, committed=0GB)
                            (mmap: reserved=1GB, committed=0GB, at peak) 
-                     Other (reserved=1GB, committed=1GB)
	[0x00000005c0000000 - 0x0000000601c00000] committed 1GB from
                             (reserved=8GB, committed=1GB Type=Java Heap)
                             (reserved=1GB, committed=0GB Type=Class)
                             (reserved=1GB, committed=0GB Type=Code)
```

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8320061](https://bugs.openjdk.org/browse/JDK-8320061) needs maintainer approval
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8320061](https://bugs.openjdk.org/browse/JDK-8320061): [nmt] Multiple issues with peak accounting (**Enhancement** - P4 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/481/head:pull/481` \
`$ git checkout pull/481`

Update a local copy of the PR: \
`$ git checkout pull/481` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/481/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 481`

View PR using the GUI difftool: \
`$ git pr show -t 481`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/481.diff">https://git.openjdk.org/jdk21u-dev/pull/481.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/481#issuecomment-2046920705)

### CODE REVIEW

**Comment by Delawen** [comment]
/clean

This is a clean merge to another open PR.

**Review by shipilev — APPROVED** [review]
Superficially, this looks good. @tstuefe should ack as well.

Have you ran `runtime/NMT` tests with this PR?

**Comment by Delawen** [comment]
Tests are being run on the github jobs right now. Once they are done I will do the approval command. Thanks @shipilev !

**Comment by shipilev** [comment]
> Tests are being run on the github jobs right now. Once they are done I will do the approval command. Thanks @shipilev !

It would be safer to run `runtime/NMT` locally, without relying on GHA to include all of them. Since this PR is modifies the tests, it is expected that you verify all of them still work reliably :)

**Comment by Delawen** [comment]
Sure, then I will run them now :)

(I did it on the original PR commit but it's true, a merge that big deserves another try)

**Comment by Delawen** [comment]
Tests passed.

Also I checked again the output again of the following commands:

```
$ jcmd 2847003 VM.native_memory detail | grep "mmap: reserved="
                            (mmap: reserved=8388608KB, committed=1236992KB, at peak) 
                            (mmap: reserved=1048576KB, committed=40384KB, at peak) 
                            (mmap: reserved=528392KB, committed=68440KB, at peak) 
                            (mmap: reserved=197140KB, committed=57460KB, at peak) 
                            (mmap: reserved=40KB, committed=36KB, at peak) 
                            (mmap: reserved=8KB, committed=8KB, at peak) 
                            (mmap: reserved=327680KB, committed=276224KB, at peak) 
                            (mmap: reserved=0KB, committed=0KB, peak=20KB) 
```

```
$ jcmd 2847003 VM.native_memory detail scale=g | grep "committed"
Total: reserved=11GB, committed=3GB
       mmap:   reserved=10GB, committed=2GB
-                 Java Heap (reserved=8GB, committed=1GB)
                            (mmap: reserved=8GB, committed=1GB, at peak) 
-                     Class (reserved=1GB, committed=0GB)
                            (mmap: reserved=1GB, committed=0GB, at peak) 
                            (    reserved=0GB, committed=0GB)
                            (    reserved=1GB, committed=0GB)
-                      Code (reserved=1GB, committed=0GB)
                            (mmap: reserved=1GB, committed=0GB, at peak) 
-                     Other (reserved=1GB, committed=1GB)
	[0x00000005c0000000 - 0x000000060c800000] committed 1GB from
                             (reserved=8GB, committed=1GB Type=Java Heap)
                             (reserved=1GB, committed=0GB Type=Class)
                             (reserved=1GB, committed=0GB Type=Code)
```

**Comment by Delawen** [comment]
/approval JDK-8320061 request Fix Request
This is a backport for https://bugs.openjdk.org/browse/JDK-8320061 ( [nmt] Multiple issues with peak accounting ). This backport fixes several NMT things, among those, the problem with largest_committed being 0KB as shown on the previous PR.

**Comment by Delawen** [comment]
@tstuefe can you take a look here?

**Comment by tstuefe** [comment]
Hi @Delawen,

thank you for doing this. Can you describe what parts of the patch you had to adapt, in order to make my review easier? Were the needed changes trivial, e.g. only comments?

**Comment by Delawen** [comment]
I didn't have to change much, just fixing a couple of trivial merge conflicts (line numbers changed and that made git ask if it was right). 

It is mostly the original backport. If you compare the [original commit](https://github.com/openjdk/jdk/commit/dc256fbc6490f8163adb286dbb7380c10e5e1e06) and this one you will see the changes shown are the same.

**Review by tstuefe — APPROVED** [review]
Thank you!

**Comment by tstuefe** [comment]
> I didn't have to change much, just fixing a couple of trivial merge conflicts (line numbers changed and that made git ask if it was right).
> 
> It is mostly the original backport. If you compare the [original commit](https://github.com/openjdk/jdk/commit/dc256fbc6490f8163adb286dbb7380c10e5e1e06) and this one you will see the changes shown are the same.

Thanks, looks good. I wish we had a tool for showing the manual changes after such a merge.

**Comment by shipilev** [comment]
Thanks both! Let's do this.

/sponsor

**Pull request closed without merging**
