### PR TITLE
8335912: Add an operation mode to the jar command when extracting to not overwriting existing files

### PR DESCRIPTION
**Pull request by alexeybakhtin**
Clean backport of jar tool enhancement from JDK23

JTREG tests passed

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8344651](https://bugs.openjdk.org/browse/JDK-8344651) to be approved
- [x] [JDK-8335912](https://bugs.openjdk.org/browse/JDK-8335912) needs maintainer approval

### Issues
 * [JDK-8335912](https://bugs.openjdk.org/browse/JDK-8335912): Add an operation mode to the jar command when extracting to not overwriting existing files (**Enhancement** - P5 - Approved)
 * [JDK-8344651](https://bugs.openjdk.org/browse/JDK-8344651): Add an operation mode to the jar command when extracting to not overwriting existing files (**CSR**)

### Reviewers
 * [Henry Jen](https://openjdk.org/census#henryjen) (@slowhog - Committer)
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1177/head:pull/1177` \
`$ git checkout pull/1177`

Update a local copy of the PR: \
`$ git checkout pull/1177` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1177/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1177`

View PR using the GUI difftool: \
`$ git pr show -t 1177`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1177.diff">https://git.openjdk.org/jdk21u-dev/pull/1177.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1177#issuecomment-2494821254)
</details>

### CODE REVIEW

**Review by slowhog — APPROVED** [review]
LGTM

**Comment by alexeybakhtin** [comment]
> LGTM

@slowhog, Thank you for review.
Can anybody with review status accept it also?

**Review by GoeLin — APPROVED** [review]
This is the same change as the pull request targeted to 23. (Not really a clean _backport_, as the PR for 23 was never pushed.)
Wrt. to the head version it adds the enum OptionType.EXTRACT, which is needed to implement flags applicable in addition to the parameter or mode "extract". JDK-8173970 adds a different flag, independent of this one.  So it's a good idea to reuse this code snippet.  Besides this the change is identical to head.

**Comment by GoeLin** [comment]
GHA failure
One is the well known wget error, unrelated.
The other is a jtreg failure, serviceability/sa/CDSJMapClstats.java fails.
ACtually it throws SIGBUS, and then terminates with 
IOException: LingeredApp terminated with non-zero exit code 137

I would not expect this change to affect CDSJMapClstats, but please have a second look and best restart this test.

**Review by martinuy — APPROVED** [review]
Thanks for this contribution. Looks good to me.

**Pull request closed without merging**
