### PR TITLE
8309203: C2: remove copy-by-value of GrowableArray for InterfaceSet

### PR DESCRIPTION
**Pull request by shipilev**
Transplanted from https://github.com/openjdk/jdk21u/pull/423

Clean backport to amend JDK 21 change, dodge the potential copy-by-value issues, and sync up codebases.

Maybe @rwestrel would bless it.

Additional testing:
 - [x] MacOS AArch64 server fastdebug, `hotspot:tier1`
 - [x] Linux x86_64 server fastdebug `tier{1,2,3}`
 - [x] Linux AArch64 server fastdebug `tier{1,2,3}`

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8309203](https://bugs.openjdk.org/browse/JDK-8309203) needs maintainer approval

### Issue
 * [JDK-8309203](https://bugs.openjdk.org/browse/JDK-8309203): C2: remove copy-by-value of GrowableArray for InterfaceSet (**Sub-task** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/11/head:pull/11` \
`$ git checkout pull/11`

Update a local copy of the PR: \
`$ git checkout pull/11` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/11/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 11`

View PR using the GUI difftool: \
`$ git pr show -t 11`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/11.diff">https://git.openjdk.org/jdk21u-dev/pull/11.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/11#issuecomment-1853701632)

### CODE REVIEW

**Comment by rwestrel** [comment]
@shipilev not sure what kind of blessing you'd like. No need to review the code if the backport is clean, right? Or are you asking if I support the idea of doing the backport? I think it's reasonable in part because it could make other backports easier going forward.

**Comment by shipilev** [comment]
> Or are you asking if I support the idea of doing the backport? I think it's reasonable in part because it could make other backports easier going forward.

Yes, that one. Thanks!

**Comment by shipilev** [comment]
/approval request Clean backport to amend JDK 21 change, dodge the potential copy-by-value issues, and sync up codebases. Tests pass.

**Comment by GoeLin** [comment]
You might want to have a look at the GHA test.

**Comment by shipilev** [comment]
> You might want to have a look at the GHA test.

That one looks environmental (macos worker died). But I pulled from the master anyway to catch more surprises, and this would re-run GHA. Let's see.

**Pull request closed without merging**
