### PR TITLE
8319818: Address GCC 13.2.0 warnings (stringop-overflow and dangling-pointer)

### PR DESCRIPTION
**Pull request by shipilev**
This batch of fixes improves the warnings handling for newer GCCs. These issues are a bit interdependent contextually, so I opted to pick them up in one batch, making it abundantly clear what are we adding.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8319818](https://bugs.openjdk.org/browse/JDK-8319818) needs maintainer approval
- [x] [JDK-8320212](https://bugs.openjdk.org/browse/JDK-8320212) needs maintainer approval
- [x] [JDK-8326717](https://bugs.openjdk.org/browse/JDK-8326717) needs maintainer approval

### Issues
 * [JDK-8319818](https://bugs.openjdk.org/browse/JDK-8319818): Address GCC 13.2.0 warnings (stringop-overflow and dangling-pointer) (**Enhancement** - P4 - Approved)
 * [JDK-8320212](https://bugs.openjdk.org/browse/JDK-8320212): Disable GCC stringop-overflow warning for affected files (**Bug** - P4 - Approved)
 * [JDK-8326717](https://bugs.openjdk.org/browse/JDK-8326717): Disable stringop-overflow in shenandoahLock.cpp (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/797/head:pull/797` \
`$ git checkout pull/797`

Update a local copy of the PR: \
`$ git checkout pull/797` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/797/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 797`

View PR using the GUI difftool: \
`$ git pr show -t 797`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/797.diff">https://git.openjdk.org/jdk21u-dev/pull/797.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/797#issuecomment-2194131523)

### CODE REVIEW

**Review by TheRealMDoerr — APPROVED** [review]
LGTM.

**Comment by shipilev** [comment]
Thanks!

**Comment by shipilev** [comment]
/approval request This batch of fixes improves the warnings handling for newer GCCs. Part of atomic 21u PR, since it contextually depends on other fixes. Risk is low: adds warnings and moves the code around. Was in mainline for months without ill effects.

**Pull request closed without merging**
