### PR TITLE
8331572: Allow using OopMapCache outside of STW GC phases

### PR DESCRIPTION
**Pull request by shipilev**
Unclean backport to improve GC and general stack walk performance when walking interpreted frames.

This is one of few backports that gets `OopMapCache` behavior similar to mainline. This makes [JDK-8335409](https://bugs.openjdk.org/browse/JDK-8335409) backport easier, because it avoids lots of conflicts, resolving which might introduce surprising bugs. Aligning this code with mainline makes accidents less likely.

The point of uncleanliness comes from the way we hook up the cleanup notifications to Service Thread. In later JDKs, [JDK-8329488](https://bugs.openjdk.org/browse/JDK-8329488) made Service Thread wake up regularly to do various cleanups. In JDK 21, we still need to hook up the clean up to the "usual" place in safepoint epilog.

Additional testing:
 - [x] Linux x86_64 server fastdebug, `all`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8331572](https://bugs.openjdk.org/browse/JDK-8331572) needs maintainer approval
- [x] Commit message must refer to an issue
- [x] [JDK-8334594](https://bugs.openjdk.org/browse/JDK-8334594) needs maintainer approval

### Issues
 * [JDK-8331572](https://bugs.openjdk.org/browse/JDK-8331572): Allow using OopMapCache outside of STW GC phases (**Enhancement** - P4 - Approved)
 * [JDK-8334594](https://bugs.openjdk.org/browse/JDK-8334594): Generational ZGC: Deadlock after OopMap rewrites in 8331572 (**Bug** - P2 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/610/head:pull/610` \
`$ git checkout pull/610`

Update a local copy of the PR: \
`$ git checkout pull/610` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/610/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 610`

View PR using the GUI difftool: \
`$ git pr show -t 610`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/610.diff">https://git.openjdk.org/jdk21u-dev/pull/610.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/610#issuecomment-2148008786)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by shipilev** [comment]
Not now, bot.

**Comment by shipilev** [comment]
/approval 8331572 request Considerably improves concurrent GC performance with lots of threads. Does not apply cleanly, since it requires some hooks into cleanup sequence in JDK 21, see PR. Provides a firmer ground for backport bugfixes in OopMapCache. All tests pass. Was in mainline for 9+ weeks. There is a little bugtail, JDK-8334594, relaxing a too strong locked signalling. The risk is medium-low: changes a common path, but comes with only a little bugtail. The performance and maintenance benefits after related follow-up backports likely outweigh that risk.

/approval 8334594 request Follow-up for JDK-8331572. Applies cleanly. All tests pass.

**Review by phohensee — APPROVED** [review]

**Comment by shipilev** [comment]
Re-ran `all` tests with all GC combinations, and they are clean.

/integrate

**Pull request closed without merging**
