### PR TITLE
8318608: Enable parallelism in vmTestbase/nsk/stress/threads tests

### PR DESCRIPTION
**Pull request by elifaslan1**
Clean backport to enable parallelism in vmTestbase/nsk/stress/threads tests.

Tested with GHA.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8318608](https://bugs.openjdk.org/browse/JDK-8318608) needs maintainer approval

### Issue
 * [JDK-8318608](https://bugs.openjdk.org/browse/JDK-8318608): Enable parallelism in vmTestbase/nsk/stress/threads tests (**Enhancement** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/136/head:pull/136` \
`$ git checkout pull/136`

Update a local copy of the PR: \
`$ git checkout pull/136` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/136/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 136`

View PR using the GUI difftool: \
`$ git pr show -t 136`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/136.diff">https://git.openjdk.org/jdk21u-dev/pull/136.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/136#issuecomment-1879161257)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi,
your approval request is not complete.
Please list reason, risk, testing and whether
the backport was clean. See also 
https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix "Example Fix Request comment".

**Comment by elifaslan1** [comment]
/approval request Enables parallelism in vmTestbase/nsk/stress/threads tests. Clean backport. Tests pass.

**Comment by elifaslan1** [comment]
I see [jdk21u-fix-yes] label in the jbs issue

/integrate

**Pull request closed without merging**
