### PR TITLE
8320707: Virtual thread test updates

### PR DESCRIPTION
**Pull request by shipilev**
Test-only backport that simplifies Loom maintenance. The original commit applies cleanly, but it does not work out of the box, because `VThreadPinner` uses FFM, which is a preview feature in JDK 21, made final in JDK 22. My attempts to soft-touch FFM into working in JDK 21 with these tests failed: x86_32's fallback linker does not work properly in JDK 21, so tests cannot complete there.

Therefore, I made a side-ways move here: rewrote `VThreadPinner` to use `synchronized`, which still pins the thread in JDK 21, and would likely continue doing so. It is unlikely we would backport the runtime changes required to avoid pinning on synchronized blocks. This is what the old tests did anyway.

This would also make subsequent backports clean.

Additional testing:
 - [x] MacOS AArch64 server fastdebug, `jdk_loom hotspot_loom`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8320707](https://bugs.openjdk.org/browse/JDK-8320707) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8320707](https://bugs.openjdk.org/browse/JDK-8320707): Virtual thread test updates (**Enhancement** - P4 - Approved)

### Reviewers
 * [Volker Simonis](https://openjdk.org/census#simonis) (@simonis - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/328/head:pull/328` \
`$ git checkout pull/328`

Update a local copy of the PR: \
`$ git checkout pull/328` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/328/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 328`

View PR using the GUI difftool: \
`$ git pr show -t 328`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/328.diff">https://git.openjdk.org/jdk21u-dev/pull/328.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/328#issuecomment-1978673705)

### CODE REVIEW

**Comment by shipilev** [comment]
GHA x86_32 tests are failing, I think we need #330 first.

**Comment by shipilev** [comment]
Grr, the x86_32 thing does not work. Getting back to draft until I can figure it out.

**Comment by shipilev** [comment]
@jerboaa, @GoeLin -- good for 21u, or?

**Comment by jerboaa** [comment]
Seems fine to me.

**Comment by shipilev** [comment]
> Seems fine to me.

Thanks!

> Being a good citizen would need a 22u backport first.

Not sure we want to do tests maintenance in a soon-to-be-dead release, but sure, here it is: https://github.com/openjdk/jdk22u/pull/160

**Review by simonis — APPROVED** [review]
Looks good!

Nice idea to use `synchronized (runner)`.

**Pull request closed without merging**
