### PR TITLE
8325028: (ch) Pipe channels should lazily set socket to non-blocking mode on first use by virtual thread

### PR DESCRIPTION
**Pull request by vpa1977**
Hi all,

This pull request contains a backport of commit [d1099033](https://github.com/openjdk/jdk/commit/d1099033ac63b9dd0dd6e3a7341db929e9e0e56e) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Alan Bateman on 8 Feb 2024 and was reviewed by Brian Burkhalter.

This change fixes a bug in jruby[1] that broken pipeline functions of Open3[1][2].
This change is high risk as there is no jtreg test *directly* testing the pipe behaviour.
Patch applies cleanly to 21u.
The patch was tested against JRuby test suite in Ubuntu. Without the patch the following tests[3] fail:
```
1) Failure:
TestOpen3#test_pipeline_start [/tmp/autopkgtest.Dz4xQk/autopkgtest_tmp/test/mri/test_open3.rb:303]:
Failed assertion, no message given.

  2) Failure:
TestOpen3#test_pipeline_w [/tmp/autopkgtest.Dz4xQk/autopkgtest_tmp/test/mri/test_open3.rb:288]:
<true> expected but was
<false>.

  3) Failure:
TestOpen3#test_capture3_flip [/tmp/autopkgtest.Dz4xQk/autopkgtest_tmp/test/mri/test_open3.rb:190]:
```
With the patch, they pass. Also the reproducer 
```
require 'open3'

RUBY = 'jruby'
Open3.pipeline_r([RUBY, '-e', 'print "1"'],
                     [RUBY, '-e', 'print STDIN.read + "2"']) {|o,ts|
      print(o.read)
    }
---
```
outputs 12 as expected in multiple runs.
There is no regression in tier1 and tier2 tests ran on Ubuntu.

Thanks!

[1] https://github.com/jruby/jruby/issues/8069
[2] https://bugs.launchpad.net/ubuntu/+source/jruby/+bug/2054943
[3] https://bugs.launchpad.net/ubuntu/+source/openjdk-21/+bug/2054943

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8325028](https://bugs.openjdk.org/browse/JDK-8325028) needs maintainer approval

### Issue
 * [JDK-8325028](https://bugs.openjdk.org/browse/JDK-8325028): (ch) Pipe channels should lazily set socket to non-blocking mode on first use by virtual thread (**Enhancement** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/290/head:pull/290` \
`$ git checkout pull/290`

Update a local copy of the PR: \
`$ git checkout pull/290` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/290/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 290`

View PR using the GUI difftool: \
`$ git pr show -t 290`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/290.diff">https://git.openjdk.org/jdk21u-dev/pull/290.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/290#issuecomment-1963329046)

### CODE REVIEW

**Comment by GoeLin** [comment]
@vpa1977 please also backport this to jdk22u.

**Comment by vpa1977** [comment]
> @vpa1977 please also backport this to jdk22u.
I apologise for forgetting this. I have created https://github.com/openjdk/jdk22u/pull/79 .

**Comment by GoeLin** [comment]
Hi @vpa1977  
please have a look at https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix to write a proper fix request comment. Removed the tag for now.

**Comment by vpa1977** [comment]
> Hi @vpa1977 please have a look at https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix to write a proper fix request comment. Removed the tag for now.

Thank you!!!
I have added the comment, but did not set the tag. Please advice if i should add more details before tagging the issue?

**Comment by shipilev** [comment]
Hey @vpa1977, the last GHA test run was back in Feburary. Please merge from master and see that GHAs are still green? After that, I can sponsor.

**Comment by vpa1977** [comment]
@shipilev Thank you!!! I've merged master and the tests passed.

**Pull request closed without merging**
