### PR TITLE
8330094: RISC-V: Save and restore FRM in the call stub

### PR DESCRIPTION
**Pull request by zifeihan**
Hi, The same issue also exists in JDK21u. So I would like to backport [JDK-8330094](https://bugs.openjdk.org/browse/JDK-8330094) to jdk21u-dev. With this change, we save and restore the default floating-point control state when we enter and leave Java code, ensuring that we are still Java compatible if we're called via the JNI invocation interface with a weird FP control state. RISC-V specific change, risk is low.
The backport is not clean because jdk21u-dev has no [JDK-8321021](https://bugs.openjdk.org/browse/JDK-8321021)

### Testing

- [x]  Run tier1-3 tests on SOPHON SG2042 (release)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8330094](https://bugs.openjdk.org/browse/JDK-8330094) needs maintainer approval

### Issue
 * [JDK-8330094](https://bugs.openjdk.org/browse/JDK-8330094): RISC-V: Save and restore FRM in the call stub (**Enhancement** - P4 - Approved)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/545/head:pull/545` \
`$ git checkout pull/545`

Update a local copy of the PR: \
`$ git checkout pull/545` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/545/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 545`

View PR using the GUI difftool: \
`$ git pr show -t 545`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/545.diff">https://git.openjdk.org/jdk21u-dev/pull/545.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/545#issuecomment-2085304711)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
LGTM.

**Comment by zifeihan** [comment]
@RealFYang @jerboaa : Thanks for the review.
/integrate

**Pull request closed without merging**
