### PR TITLE
8334239: Introduce macro for ubsan method/function exclusions

### PR DESCRIPTION
**Pull request by luwang1103**
hi  @shipilev ,

This pull request contains a backport of commit [ff30240](https://git.openjdk.org/jdk/commit/ff30240926224b2f98e173bcd606c157af788919) from the [master](https://github.com/openjdk/jdk) repository.

The commit being backported was authored by Matthias Baesken on 20 Jun 2024.

Thanks！

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8334239](https://bugs.openjdk.org/browse/JDK-8334239) needs maintainer approval

### Issue
 * [JDK-8334239](https://bugs.openjdk.org/browse/JDK-8334239): Introduce macro for ubsan method/function exclusions (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/834/head:pull/834` \
`$ git checkout pull/834`

Update a local copy of the PR: \
`$ git checkout pull/834` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/834/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 834`

View PR using the GUI difftool: \
`$ git pr show -t 834`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/834.diff">https://git.openjdk.org/jdk21u-dev/pull/834.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/834#issuecomment-2221926782)

### CODE REVIEW

**Comment by shipilev** [comment]
Yes, but why it is not clean? Because [JDK-8332818](https://bugs.openjdk.org/browse/JDK-8332818) and [JDK-8333887](https://bugs.openjdk.org/browse/JDK-8333887) are not present in jdk21u-dev? Sorry to drag this on, but I think we are better to backport those as well. You can do them as separate PRs.

**Comment by tstuefe** [comment]
Seeing that the hit-to-miss ratio of ubsan is somewhat meh, do we even want to backport this potentially long chain of ubsan issues?

**Comment by shipilev** [comment]
> Seeing that the hit-to-miss ratio of ubsan is somewhat meh, do we even want to backport this potentially long chain of ubsan issues?

All of them? Probably not.

Enough of them to make fixes that make UBSAN not breaking the builds, like https://github.com/openjdk/jdk21u-dev/pull/828? Yes.

**Comment by shipilev** [comment]
Now, if you rebase on new master, would this PR be clean?

**Comment by shipilev** [comment]
Ah, OK, it misses hunks from the original changeset. Reapply the changeset and force-push? The PR should contain a single commit that matches the mainline one (https://github.com/openjdk/jdk/commit/ff30240926224b2f98e173bcd606c157af788919) -- then the PR should be clean.

**Comment by luwang1103** [comment]
/approval request The code applies cleanly. Low risk: It is a corner case which is not triggered by the current code. In order to avoid bugs in the future, it is good to backport it.

**Comment by shipilev** [comment]
This can be integrated now, I think.

**Comment by luwang1103** [comment]
@shipilev  Can you please sponsor the changes? thanks

**Pull request closed without merging**
