### PR TITLE
8325525: Create jtreg test case for JDK-8325203

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 21.0.5-oracle.

I include follow-up 8336315.

Both are clean backports.  Test passes on win.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8336315](https://bugs.openjdk.org/browse/JDK-8336315) needs maintainer approval
- [x] [JDK-8325525](https://bugs.openjdk.org/browse/JDK-8325525) needs maintainer approval

### Issues
 * [JDK-8325525](https://bugs.openjdk.org/browse/JDK-8325525): Create jtreg test case for JDK-8325203 (**Enhancement** - P4 - Approved)
 * [JDK-8336315](https://bugs.openjdk.org/browse/JDK-8336315): tools/jpackage/windows/WinChildProcessTest.java Failed: Check is calculator process is alive (**Bug** - P4 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1160/head:pull/1160` \
`$ git checkout pull/1160`

Update a local copy of the PR: \
`$ git checkout pull/1160` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1160/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1160`

View PR using the GUI difftool: \
`$ git pr show -t 1160`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1160.diff">https://git.openjdk.org/jdk21u-dev/pull/1160.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1160#issuecomment-2483208572)
</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
@kevinrushforth, thanks, I mistyped the bugid.

**Comment by GoeLin** [comment]
GHA failure: infra issue, unrelated.
Error: sh][ERROR] wget exited with exit code 4

**Review by RealLucy — APPROVED** [review]
LGTM.

**Pull request closed without merging**
