### PR TITLE
8331153: JFR: Improve logging of jdk/jfr/api/consumer/filestream/TestOrdered.java

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,

This pull request contains a backport of commit [f3bb3e21](https://github.com/openjdk/jdk/commit/f3bb3e21704dd47c6c5d5753ca5882520a538c06) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Erik Gahlin on 26 Apr 2024 and was reviewed by Markus Grönlund.

This the prefixed backport of [JDK-8323196](https://bugs.openjdk.org/browse/JDK-8323196).

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8331153](https://bugs.openjdk.org/browse/JDK-8331153) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8331153](https://bugs.openjdk.org/browse/JDK-8331153): JFR: Improve logging of jdk/jfr/api/consumer/filestream/TestOrdered.java (**Sub-task** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/915/head:pull/915` \
`$ git checkout pull/915`

Update a local copy of the PR: \
`$ git checkout pull/915` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/915/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 915`

View PR using the GUI difftool: \
`$ git pr show -t 915`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/915.diff">https://git.openjdk.org/jdk21u-dev/pull/915.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/915#issuecomment-2285263614)

### CODE REVIEW

**Comment by sendaoYan** [comment]
/approval request Clean backport, to improves logging of a test to be able to debug failures more easily.

**Comment by jerboaa** [comment]
@sendaoYan Please provide some rationale why this debugging in a test is needed. Do you actually see test failures? Why are you backporting this?

**Comment by sendaoYan** [comment]
> @sendaoYan Please provide some rationale why this debugging in a test is needed. Do you actually see test failures? Why are you backporting this?

Hi, we have observed this test intermittent failure, which seems similar to [JDK-8323196](https://bugs.openjdk.org/browse/JDK-8323196). So we want to backport [JDK-8323196](https://bugs.openjdk.org/browse/JDK-8323196), and this PR is the prefixed backport of [JDK-8323196](https://bugs.openjdk.org/browse/JDK-8323196).

**Comment by sendaoYan** [comment]
/approval request Clean backport, to improves logging of a test to be able to debug failures more easily. We have observed this test intermittent failure, which seems similar to [JDK-8323196](https://bugs.openjdk.org/browse/JDK-8323196). So we want to backport [JDK-8323196](https://bugs.openjdk.org/browse/JDK-8323196), and this PR is the prefixed backport of [JDK-8323196](https://bugs.openjdk.org/browse/JDK-8323196). Test fix only, no risk.

**Comment by sendaoYan** [comment]
> /approve yes

Thanks for the approval.

/integrate

**Comment by sendaoYan** [comment]
Thanks for the sponsor.

**Pull request closed without merging**
