### PR TITLE
8322142: JFR: Periodic tasks aren't orphaned between recordings

### PR DESCRIPTION
**Pull request by antonha**
Backport to fix https://bugs.openjdk.org/browse/JDK-8322142 for jdk21. 

First time commiting to openjdk, so please pardon if this is the wrong approach to the PR. I followed instructions in https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix - not sure if those are still valid for 21.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8322142](https://bugs.openjdk.org/browse/JDK-8322142) needs maintainer approval

### Issue
 * [JDK-8322142](https://bugs.openjdk.org/browse/JDK-8322142): JFR: Periodic tasks aren't orphaned between recordings (**Bug** - P2 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/203/head:pull/203` \
`$ git checkout pull/203`

Update a local copy of the PR: \
`$ git checkout pull/203` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/203/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 203`

View PR using the GUI difftool: \
`$ git pr show -t 203`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/203.diff">https://git.openjdk.org/jdk21u-dev/pull/203.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/203#issuecomment-1906618881)

### CODE REVIEW

**Comment by antonha** [comment]
/approval JDK-8322142 request This issue affects production flight recording rather severely, it would be useful to have the fix in 21 as well.

**Comment by jerboaa** [comment]
@antonha What testing have you done? Please enable GHA for your fork (minimum bar to get it integrated). Running JFR tests would be wise to do as well. Thanks!

**Comment by jerboaa** [comment]
The fix request comment didn't mention it so I'm removing the approval label for now. Please re-apply once that's present/fixed.

**Comment by antonha** [comment]
@jerboaa Thanks - I did run the tier1 suite locally before creating the PR. I also enabled GHA for the for the fork, but did that after creating the PR so I don't think that it automatically triggered - I did a run which seems to have passed: https://github.com/antonha/jdk21u-dev/actions/runs/7646727789

I'm not that familiar with the test suite so I don't quite know which JFR tests there are, but I did now try running the `jdk/jfr` tests using `make run-test TEST=jdk/jfr` for `linux-x86_64-server-release` and `linux-x86_64-server-fastdebug` locally, both pass with the same message:

```bash
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/jdk/jdk/jfr                              584   584     0     0   
==============================
TEST SUCCESS
```

Should I re-apply for approval now?

**Comment by jerboaa** [comment]
@antonha Thanks!

> Should I re-apply for approval now?

Yes. Mention the testing you've done in the approval comment.

**Comment by antonha** [comment]
/approval JDK-8322142 request GHA sanity checks passed (https://github.com/antonha/jdk21u-dev/actions/runs/7646727789). `make run-test TEST=jdk/jfr` passes for  `linux-x86_64-server-release` and `linux-x86_64-server-fastdebug` on my desktop.

**Comment by jerboaa** [comment]
Thanks for the update. Fix request comment was better now. Affects JFR usage only => low risk with rather high impact. Approved.

**Pull request closed without merging**
