### PR TITLE
8310913: Move ReferencedKeyMap to jdk.internal so it may be shared

### PR DESCRIPTION
**Pull request by shipilev**
Unclean backport to match the codebases between mainline and JDK 21, simplifying maintenance. It also implicitly fixes [JDK-8323505](https://bugs.openjdk.org/browse/JDK-8323505), since this move includes a few touchups to the test.

The uncleanliness comes from `MethodType.java` conflicts that does not have [JDK-8310849](https://bugs.openjdk.org/browse/JDK-8310849) in JDK 21. So it yields a few contextual conflicts. Since affected hunks are just removals, I removed them by hand.

There is a follow-up, [JDK-8325255](https://bugs.openjdk.org/browse/JDK-8325255), but it does not seem to affect anything yet, since there are no `ReferenceKeySet.add` calls anywhere in sight. We can backport that separately.

Additional testing:
 - [x] MacOS AArch64 Server fastdebug, `jdk/internal/util` tests pass
 - [x] MacOS AArch64 Server fastdebug, `java/lang/invoke` tests pass
 - [x] Linux AArch64 Server fastdebug, `all` tests pass

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8310913](https://bugs.openjdk.org/browse/JDK-8310913) needs maintainer approval

### Issue
 * [JDK-8310913](https://bugs.openjdk.org/browse/JDK-8310913): Move ReferencedKeyMap to jdk.internal so it may be shared (**Enhancement** - P3 - Approved)

### Reviewers
 * [Richard Reingruber](https://openjdk.org/census#rrich) (@reinrich - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/342/head:pull/342` \
`$ git checkout pull/342`

Update a local copy of the PR: \
`$ git checkout pull/342` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/342/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 342`

View PR using the GUI difftool: \
`$ git pr show -t 342`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/342.diff">https://git.openjdk.org/jdk21u-dev/pull/342.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/342#issuecomment-1997457068)

### CODE REVIEW

**Comment by shipilev** [comment]
RISC-V GHA failure is environmental.

**Comment by reinrich** [comment]
> There is a follow-up, [JDK-8325255](https://bugs.openjdk.org/browse/JDK-8325255), but it does not seem to affect anything yet, since there are no ReferenceKeySet.add calls anywhere in sight. We can backport that separately.

Don't you think that will be forgotten?

**Comment by shipilev** [comment]
> > There is a follow-up, [JDK-8325255](https://bugs.openjdk.org/browse/JDK-8325255), but it does not seem to affect anything yet, since there are no ReferenceKeySet.add calls anywhere in sight. We can backport that separately.
> 
> Don't you think that will be forgotten?

Not sure what do you mean.

**Comment by shipilev** [comment]
> Likely a misunderstanding on my side: I thought you did not want to backport [JDK-8325255](https://bugs.openjdk.org/browse/JDK-8325255) until `ReferenceKeySet` is referenced. But you're going to do the backport soon after this backport, correct?

Yes. I was merely pointing out that we don't _have_ to backport JDK-8325255 along with JDK-8310913 atomically, because it technically does not break anything yet. Otherwise we would need to cobble together JDK-8325255 and JDK-8310913 into an atomic integration to avoid any breakage window.

Since you are here, maybe you would like to Review this PR? I jumped a gun a little here and got approval before RFR was formally reviewed, and I still cannot integrate :) I'll pull from master momentarily.

**Comment by reinrich** [comment]
This inquiry is part of my review :)
I'm going to approve now...

**Review by reinrich — APPROVED** [review]
The backport looks good.
Please make sure not to forget the follow-up [JDK-8325255](https://bugs.openjdk.org/browse/JDK-8325255).

Cheers, Richard.

**Comment by shipilev** [comment]
> The backport looks good. 

Thanks! I am re-running tests now, and will integrate once they turn up green.

> Please make sure not to forget the follow-up [JDK-8325255](https://bugs.openjdk.org/browse/JDK-8325255).

Yes, I plan to propose it after integrating this one.

**Pull request closed without merging**
