### PR TITLE
8073061: (fs) Files.copy(foo, bar, REPLACE_EXISTING) deletes bar even if foo is not readable

### PR DESCRIPTION
**Pull request by toddjonker**
This is a clean backport of https://github.com/openjdk/jdk/commit/36ac83904c9e81a01822b0e36ef677cae2808709 originally authored by @bplb and reviewed by @AlanBateman  

It also includes this follow-up fix:
  * [JDK-8317128](https://bugs.openjdk.org/browse/JDK-8317128): **java/nio/file/Files/CopyAndMove.java failed with AccessDeniedException** 
      * https://github.com/openjdk/jdk/pull/15991

Additional testing:
- [x] New regression test fails without the fix, passes with it
- [x] linux-x86_64-server-release: `JTREG_KEYWORDS="\!headful & \!external-dep & \!printer" make test TEST="tier1 tier2 tier3"`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8317128](https://bugs.openjdk.org/browse/JDK-8317128) needs maintainer approval
- [x] Commit message must refer to an issue
- [x] [JDK-8073061](https://bugs.openjdk.org/browse/JDK-8073061) needs maintainer approval

### Issues
 * [JDK-8073061](https://bugs.openjdk.org/browse/JDK-8073061): (fs) Files.copy(foo, bar, REPLACE_EXISTING) deletes bar even if foo is not readable (**Bug** - P4 - Approved)
 * [JDK-8317128](https://bugs.openjdk.org/browse/JDK-8317128): java/nio/file/Files/CopyAndMove.java failed with AccessDeniedException (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/863/head:pull/863` \
`$ git checkout pull/863`

Update a local copy of the PR: \
`$ git checkout pull/863` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/863/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 863`

View PR using the GUI difftool: \
`$ git pr show -t 863`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/863.diff">https://git.openjdk.org/jdk21u-dev/pull/863.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/863#issuecomment-2278665606)

### CODE REVIEW

**Comment by toddjonker** [comment]
Putting back into draft; I missed the follow-up fix https://bugs.openjdk.org/browse/JDK-8317128

**Review by phohensee — APPROVED** [review]

**Comment by toddjonker** [comment]
/approval request 8073061 Backport of data-loss defect in Files.copy(); originally authored by @bplb and reviewed by @AlanBateman
Passes headless tests tiers 1-3

**Comment by toddjonker** [comment]
/approval request 8317128 Backport of bugfix for regression caused by JDK-8073061

 Passes headless tests tiers 1-3

**Comment by toddjonker** [comment]
/approval 8073061 request Backport of data-loss defect in Files.copy(); originally authored by @bplb and reviewed by @AlanBateman
Passes headless tests tiers 1-3

**Comment by toddjonker** [comment]
/approval 8317128 request  Backport of bugfix for regression caused by JDK-8073061

Passes headless tests tiers 1-3

**Pull request closed without merging**
