### PR TITLE
8294699: Launcher causes lingering busy cursor

### PR DESCRIPTION
**Pull request by lutkerd**
Backport for parity with Oracle 21.0.4

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8294699](https://bugs.openjdk.org/browse/JDK-8294699) needs maintainer approval

### Issue
 * [JDK-8294699](https://bugs.openjdk.org/browse/JDK-8294699): Launcher causes lingering busy cursor (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/327/head:pull/327` \
`$ git checkout pull/327`

Update a local copy of the PR: \
`$ git checkout pull/327` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/327/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 327`

View PR using the GUI difftool: \
`$ git pr show -t 327`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/327.diff">https://git.openjdk.org/jdk21u-dev/pull/327.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/327#issuecomment-1977069425)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @lutkerd, your fix-request comment is meaningless, and you have failing tests. Please follow https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix. Removing the tag.

**Comment by lwahonen** [comment]
The failing tests are for linux-x86 but the backport only touches a single .cpp in the Windows components. I think the test failure is a false positive?

**Comment by lwahonen** [comment]
@GoeLin  Can we get this merged please?

**Comment by jerboaa** [comment]
> Parity with Oracle 21.0.4

@lutkerd I concur on the issue of more meaningful "Fix Request" comments. Those comments are supposed to reason about why it's needed as a backport, what issue it solves, assess the risk, what testing has been done etc. Simply `Parity with Oracle 21.0.4` isn't quite helpful since when looking at the bug, one can see that as well. Please keep that in mind next time.

**Comment by lutkerd** [comment]
Sorry, I've been out of the office a bit. We have a customer request for this, https://github.com/corretto/corretto-21/issues/51.

**Pull request closed without merging**
