### PR TITLE
8309894: compiler/vectorapi/VectorLogicalOpIdentityTest.java fails on SVE system with UseSVE=0

### PR DESCRIPTION
**Pull request by cost0much**
Backport that aligns the IR testing framework preconditions rule with JDK22. This mainly aims to make future backports involving the IR testing framework more convenient; more specifically to my use-case, I'd like to backport [JDK-8280120](https://bugs.openjdk.org/browse/JDK-8280120) afterwards, and this change precedes that for IREncodingPrinter.java. Not clean because [JDK-8310308](https://github.com/openjdk/jdk21u-dev/pull/29) has already backported a later fix to VectorLogicalOpIdentityTest.java.

Passes tier1 tests on Linux x86 and the test TestPreconditions.java for the framework rule change.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8309894](https://bugs.openjdk.org/browse/JDK-8309894) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309894](https://bugs.openjdk.org/browse/JDK-8309894): compiler/vectorapi/VectorLogicalOpIdentityTest.java fails on SVE system with UseSVE=0 (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/922/head:pull/922` \
`$ git checkout pull/922`

Update a local copy of the PR: \
`$ git checkout pull/922` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/922/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 922`

View PR using the GUI difftool: \
`$ git pr show -t 922`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/922.diff">https://git.openjdk.org/jdk21u-dev/pull/922.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/922#issuecomment-2291845757)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by cost0much** [comment]
/approval request Updates the preconditions rule for the IR testing framework to match JDK22. Does not apply cleanly but only due to a prior backport: resolution just involves keeping current code. Risk is very low: only applies to testing framework and no changes to any previous test code.

**Comment by GoeLin** [comment]
Hi,
I had a look at approving this. I don't understand why you omit the Copyright change to the 4th file.

**Comment by cost0much** [comment]
> Hi, I had a look at approving this. I don't understand why you omit the Copyright change to the 4th file.

Ah I assumed that since no other changes were being made to the file, that the Copyright year change should be omitted as well. I'll add it now

**Review by phohensee — APPROVED** [review]

**Pull request closed without merging**
