### PR TITLE
8195675: Call to insertText with single character from custom Input Method ignored

### PR DESCRIPTION
**Pull request by srl295**
- Backport of JDK-8195675
- Backport of https://github.com/openjdk/jdk/commit/b8f2ec9091f9f7e5f4611991d04dd8aa113b94fd https://github.com/openjdk/jdk/pull/17921

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8195675](https://bugs.openjdk.org/browse/JDK-8195675) needs maintainer approval

### Issue
 * [JDK-8195675](https://bugs.openjdk.org/browse/JDK-8195675): Call to insertText with single character from custom Input Method ignored (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1052/head:pull/1052` \
`$ git checkout pull/1052`

Update a local copy of the PR: \
`$ git checkout pull/1052` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1052/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1052`

View PR using the GUI difftool: \
`$ git pr show -t 1052`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1052.diff">https://git.openjdk.org/jdk21u-dev/pull/1052.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1052#issuecomment-2411775594)

### CODE REVIEW

**Comment by srl295** [comment]
@prrace can I get a review here?

**Comment by srl295** [comment]
>  ⚠️ Issue of type Backport is not allowed for integrations

Thought I was following https://openjdk.org/projects/jdk-updates/approval.html - do I use the original JBS number instead of creating a Backport issue?

**Comment by srl295** [comment]
No code change - just restructured so it's an actual cherry-pick.

**Comment by aivanov-jdk** [comment]
> > ⚠️ Issue of type Backport is not allowed for integrations
> 
> Thought I was following https://openjdk.org/projects/jdk-updates/approval.html - do I use the original JBS number instead of creating a Backport issue?

You should set the title of the PR to `Backport <hash>` where *`<hash>`* is the real hash of the changeset you're backporting. In this case, the title should be `Backport b8f2ec9091f9f7e5f4611991d04dd8aa113b94fd`.

(For some reason, I cannot see this information in the Guide https://openjdk.org/guide/#backporting )

If the backport is clean, the Skara bot will add the *clean* label and will allow you to integrate the backport without requiring a code review after it's approved.

**Comment by srl295** [comment]
right - the bug isn't approved yet for backport. It's clean though.

**Comment by GoeLin** [comment]
Hi,
please add the Fix request comment to the real bug, not the Backport issue you opened. Please mention 21 as target.

**Comment by srl295** [comment]
Ok.

**Comment by GoeLin** [comment]
Hi,
what tests did you run to 
1. assure this fixes the issue in 21, too.
2. you do not introduce a regression in 21 ?
Usually you mention this in the Fix request comment (which you can edit). You can also 
get the comment replaced by issueing a new approval command here in the PR if the first comment was generated by the command, too.

**Comment by srl295** [comment]
@GoeLin thanks.  The issue was filed against JDK 8 and was present in current main also. So there is that.

As to testing, it seems on Mac Sonoma I'm currently unable to build any of the repos (even the one I used to test when merging months ago.). Various issues.  I will keep trying, though.

**Comment by GoeLin** [comment]
One more thing, I should have seen that in first place. Please enable GitHub actions on this repo so we get tests.
If you merge head into your branch, the tests will restart.
(Similar for your change in 17u etc if it is not enabled there.)

**Comment by srl295** [comment]
@GoeLin i had enabled but probably after the push

**Comment by srl295** [comment]
only failure so far was wget- retrying

**Comment by srl295** [comment]
@GoeLin I've now tested this PR and it fixes the issue while allowing text input properly

image

**Comment by GoeLin** [comment]
Hi  @srl295 , I think you can /integrate this now?

**Comment by srl295** [comment]
@GoeLin Hi, what about the 8 11 and 17 backports?  21 was the only one that I manually created a backport JBS for. It looks like https://bugs.openjdk.org/browse/JDK-8195675 is `-request` still for 8, 11, and 17.

**Pull request closed without merging**
