### PR TITLE
8339725: Concurrent GC crashed due to GetMethodDeclaringClass

### PR DESCRIPTION
**Pull request by mmyxym**
Backport of fixing concurrent GC crashed due to GetMethodDeclaringClass. Not clean because of make file.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8339725](https://bugs.openjdk.org/browse/JDK-8339725) needs maintainer approval

### Issue
 * [JDK-8339725](https://bugs.openjdk.org/browse/JDK-8339725): Concurrent GC crashed due to GetMethodDeclaringClass (**Bug** - P3 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1004/head:pull/1004` \
`$ git checkout pull/1004`

Update a local copy of the PR: \
`$ git checkout pull/1004` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1004/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1004`

View PR using the GUI difftool: \
`$ git pr show -t 1004`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1004.diff">https://git.openjdk.org/jdk21u-dev/pull/1004.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1004#issuecomment-2370037860)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]
It might be too fresh to go into jdk21u-dev, but on the other hand, the fix looks simple.

**Comment by mmyxym** [comment]
/approval request Backport of fixing concurrent GC crashed due to GetMethodDeclaringClass. Not clean because of make file. The fix is quite safe with only 1 line to keep class alive so the risk is very low.

**Pull request closed without merging**
