### PR TITLE
8320343: Generate GIF images for AbstractButton/5049549/bug5049549.java

### PR DESCRIPTION
**Pull request by SoniaZaldana**
Hi all,

This pull request contains a backport of commit [9481d06e](https://github.com/openjdk/jdk/commit/9481d06e62334872af539ccfb8c1ea25e30a6da3) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Renjith Kannath Pariyangad on 2 Jan 2024 and was reviewed by Alexey Ivanov.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8320343](https://bugs.openjdk.org/browse/JDK-8320343) needs maintainer approval

### Issue
 * [JDK-8320343](https://bugs.openjdk.org/browse/JDK-8320343): Generate GIF images for AbstractButton/5049549/bug5049549.java (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/165/head:pull/165` \
`$ git checkout pull/165`

Update a local copy of the PR: \
`$ git checkout pull/165` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/165/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 165`

View PR using the GUI difftool: \
`$ git pr show -t 165`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/165.diff">https://git.openjdk.org/jdk21u-dev/pull/165.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/165#issuecomment-1938997466)

### CODE REVIEW

**Comment by SoniaZaldana** [comment]
I have verified the GHA failure is not related to the backport. I have a successful run in a personal branch (https://github.com/SoniaZaldana/jdk21u-dev/actions/runs/7890867343). Could reviewers please advise on how to re-run the GHA job on the bot branch?

**Comment by SoniaZaldana** [comment]
Hi @GoeLin, I don't seem to have write access for the bot fork so I'm unable to sync the fork or re-run any actions.

**Comment by shipilev** [comment]
It looks to me that `compiler/intrinsics/TestLongUnsignedDivMod.java` had failed on `macos-x64`. This deserves a separate follow-up, but I don't think this is an integration blocker.

**Comment by GoeLin** [comment]
@SoniaZaldana, seems your re-run workde. We now only see the well known Risk-V issue. Is there anything else keeping you from integrating this?

**Comment by SoniaZaldana** [comment]
> @SoniaZaldana, seems your re-run workde. We now only see the well known Risk-V issue. Is there anything else keeping you from integrating this?

No, I was just waiting to see if the Risk-V issue got resolved. I'll integrate.

**Comment by shipilev** [comment]
There is no need to wait for RISC-V GHA to get green.

/sponsor

**Pull request closed without merging**
