### PR TITLE
8341194: [REDO] Implement C2 VectorizedHashCode on AArch64

### PR DESCRIPTION
**Pull request by chadrako**
Backport [JDK-8341194](https://bugs.openjdk.org/browse/JDK-8341194) [REDO] Implement C2 VectorizedHashCode on AArch64

Backport is clean. Trivial merge conflicts with includes and already present code. Original implementation [JDK-8322770](https://bugs.openjdk.org/browse/JDK-8322770) caused build and test failures. Build failures that were reproducible with `make bootcycle-images` run on `linux-aarch64 fastdebug/release` successfully. All jtreg and new asmtest pass on `linux-aarch64 release`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8341194](https://bugs.openjdk.org/browse/JDK-8341194) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8341194](https://bugs.openjdk.org/browse/JDK-8341194): [REDO] Implement C2 VectorizedHashCode on AArch64 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1170/head:pull/1170` \
`$ git checkout pull/1170`

Update a local copy of the PR: \
`$ git checkout pull/1170` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1170/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1170`

View PR using the GUI difftool: \
`$ git pr show -t 1170`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1170.diff">https://git.openjdk.org/jdk21u-dev/pull/1170.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1170#issuecomment-2489413784)
</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by chadrako** [comment]
/approval request Clean backport to add C2 VectorizedHashCode on AArch64 for performance improvements. The change has been verified with all jtreg tests tiers on linux-aarch64 release and linux-aarch64 fastdebug

**Comment by GoeLin** [comment]
Hi,
I would like to defer this to the April release.
It is an enhancement and rather new. That way it will have at lease some coverage by 24,

**Comment by phohensee** [comment]
Reasonable. :)

**Pull request closed without merging**
