### PR TITLE
8321075: RISC-V: UseSystemMemoryBarrier lacking proper OS support

### PR DESCRIPTION
**Pull request by luhenry**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8321075](https://bugs.openjdk.org/browse/JDK-8321075) needs maintainer approval

### Issue
 * [JDK-8321075](https://bugs.openjdk.org/browse/JDK-8321075): RISC-V: UseSystemMemoryBarrier lacking proper OS support (**Bug** - P4 - Approved)

### Reviewers
 * [Robbin Ehn](https://openjdk.org/census#rehn) (@robehn - Committer)
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/294/head:pull/294` \
`$ git checkout pull/294`

Update a local copy of the PR: \
`$ git checkout pull/294` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/294/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 294`

View PR using the GUI difftool: \
`$ git pr show -t 294`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/294.diff">https://git.openjdk.org/jdk21u-dev/pull/294.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/294#issuecomment-1966092333)

### CODE REVIEW

**Comment by RealFYang** [comment]
@luhenry : I see the GHA testing is skipped. I think you should configure and enable GHA actions for your fork.

**Comment by luhenry** [comment]
Tests are running at https://github.com/luhenry/jdk21u-dev/actions/runs/8077938780

**Comment by luhenry** [comment]
The linux-riscv64 fails on creating the sysroot which is completely unrelated to this change. I've merged `openjdk:master` again to trigger a new CI run and hoping it'll pass this time.

**Comment by RealFYang** [comment]
> The linux-riscv64 fails on creating the sysroot which is completely unrelated to this change. I've merged `openjdk:master` again to trigger a new CI run and hoping it'll pass this time.

Yeah, it's a GHA infrastructural issue. The Debian SID is broken for now: https://bugs.openjdk.org/browse/JDK-8326960

**Comment by luhenry** [comment]
> Yeah, it's a GHA infrastructural issue. The Debian SID is broken for now: https://bugs.openjdk.org/browse/JDK-8326960

Good catch!

**Review by robehn — APPROVED** [review]
Thank!

**Comment by luhenry** [comment]
@RealFYang as the CI is still busted until Debian fixes it, we won't be able to get a green checks. Are you good to approve/merge this change?

**Comment by RealFYang** [comment]
> @RealFYang as the CI is still busted until Debian fixes it, we won't be able to get a green checks. Are you good to approve/merge this change?

Yeah. I am OK assuming linux-riscv64 builds fine on your side.
The Debian people are busy sorting things out. I gues it might take weeks for Debian SID to become debootstrappable again on all CPU platforms.

**Review by RealFYang — APPROVED** [review]

**Comment by RealFYang** [comment]
@luhenry : FYI: I think the GHA linux-cross-compile is back working again. So you might want to merge master and retrigger the GHA.

**Pull request closed without merging**
