### PR TITLE
8313816: Accessing jmethodID might lead to spurious crashes

### PR DESCRIPTION
**Pull request by jbachorik**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8313816](https://bugs.openjdk.org/browse/JDK-8313816) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313816](https://bugs.openjdk.org/browse/JDK-8313816): Accessing jmethodID might lead to spurious crashes (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/56/head:pull/56` \
`$ git checkout pull/56`

Update a local copy of the PR: \
`$ git checkout pull/56` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/56/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 56`

View PR using the GUI difftool: \
`$ git pr show -t 56`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/56.diff">https://git.openjdk.org/jdk21u-dev/pull/56.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/56#issuecomment-1859946593)

### CODE REVIEW

**Comment by jerboaa** [comment]
@jbachorik Please explain what testing you've done. Did you run all serviceability tests with this patch?

**Comment by jbachorik** [comment]
@jerboaa All pre-submit tests in GHA plus tier2, tier3 and jdk_svc on a linux x64 box

**Comment by jerboaa** [comment]
> @jerboaa All pre-submit tests in GHA plus tier2, tier3 and jdk_svc on a linux x64 box

Thanks. Approved.

**Comment by jbachorik** [comment]
Thanks @jerboaa !

**Pull request closed without merging**
