### PR TITLE
8325194: GHA: Add macOS M1 testing

### PR DESCRIPTION
**Pull request by gdams**
Now that macOS M1 executors are [available in GitHub actions](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/) it makes sense to move the build to run on M1 (rather than cross-compiled) and also enable testing on the platform.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8325194](https://bugs.openjdk.org/browse/JDK-8325194) needs maintainer approval
- [x] Commit message must refer to an issue
- [x] [JDK-8325444](https://bugs.openjdk.org/browse/JDK-8325444) needs maintainer approval

### Issues
 * [JDK-8325194](https://bugs.openjdk.org/browse/JDK-8325194): GHA: Add macOS M1 testing (**Enhancement** - P4 - Approved)
 * [JDK-8325444](https://bugs.openjdk.org/browse/JDK-8325444): GHA: JDK-8325194 causes a regression (**Bug** - P3 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/238/head:pull/238` \
`$ git checkout pull/238`

Update a local copy of the PR: \
`$ git checkout pull/238` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/238/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 238`

View PR using the GUI difftool: \
`$ git pr show -t 238`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/238.diff">https://git.openjdk.org/jdk21u-dev/pull/238.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/238#issuecomment-1930083194)

### CODE REVIEW

**Comment by gdams** [comment]
@shipilev still seeing the same error:

```output
realpath: bootjdk/jdk: No such file or directory
```

I'm slightly confused but I'll do some investigation

**Comment by shipilev** [comment]
We really need to figure out what is missing in JDK repos for this, instead of diverging. We are waiting for https://bugs.openjdk.org/browse/JDK-8324723 to land first to get the msys2 update...

**Comment by RealCLanger** [comment]
You should inline the backport of https://bugs.openjdk.org/browse/JDK-8325444 into this. And wait for https://bugs.openjdk.org/browse/JDK-8324723 of course.

**Comment by shipilev** [comment]
...and by "inline", I think it would be better to add another commit carrying https://bugs.openjdk.org/browse/JDK-8325444, and say `/issue add JDK-8325444`. This would make this PR an atomic 2-commit backport.

**Comment by gdams** [comment]
The test failures will be fixed by merging https://github.com/openjdk/jdk21u-dev/pull/254

**Comment by gdams** [comment]
/approval request backport applies cleanly (except for obvious boot JDK URL changes), affects CI only

**Comment by gdams** [comment]
> You should inline the backport of https://bugs.openjdk.org/browse/JDK-8325444 into this. And wait for https://bugs.openjdk.org/browse/JDK-8324723 of course.

I've added the second backport. As for waiting for JDK-8324723, I don't think this is necessary anymore as the build/test is passing in it's current state. CC @shipilev?

**Comment by shipilev** [comment]
> JDK-8324723

Yes, I don't think it needs to wait for JDK-8324723.

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
