### PR TITLE
8321025: Enable Neoverse N1 optimizations for Neoverse V2

### PR DESCRIPTION
**Pull request by pengxiaolong**
### Notes
Backport 8321025: Enable Neoverse N1 optimizations for Neoverse V2  to jdk21 it is not a clean backport, the method ```model_is(0xd40) ``` is in jdk21, equivalent code in jdk21 is like ```(_model == 0xd40 || _model2 == 0xd40)```.

#### Verification
Not able to test it on CPU with Neoverse V2, since I don't have server supports Neoverse V2 yet, but the fix has been backported to [Amazon Corretto 21](https://github.com/corretto/corretto-21/blob/release-21.0.3.9.1/CHANGELOG.md
) since January 16, 2024, overall it should be a low risk.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8321025](https://bugs.openjdk.org/browse/JDK-8321025) needs maintainer approval

### Issue
 * [JDK-8321025](https://bugs.openjdk.org/browse/JDK-8321025): Enable Neoverse N1 optimizations for Neoverse V2 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/720/head:pull/720` \
`$ git checkout pull/720`

Update a local copy of the PR: \
`$ git checkout pull/720` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/720/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 720`

View PR using the GUI difftool: \
`$ git pr show -t 720`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/720.diff">https://git.openjdk.org/jdk21u-dev/pull/720.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/720#issuecomment-2176620282)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]

**Comment by pengxiaolong** [comment]
Thanks Aleksey for reviewing the PR and the suggestions!

**Comment by pengxiaolong** [comment]
/approval request Backport [JDK-8321025](https://bugs.openjdk.org/browse/JDK-8321025) to jdk21 for to enable Neoverse N1 optimizations for Neoverse V2, it was not a clean backport, also backported VM_Version::model_is from [openjdk/jdk@3283328](https://github.com/openjdk/jdk/commit/3283328) when resolving the conflicts. Risk should be low, it was backported to Correto-jdk-21 in Jan 2024, no known issue so far.

**Comment by pengxiaolong** [comment]
Thanks all! I'll start integrate.

**Pull request closed without merging**
