### PR TITLE
8315559: Delay TempSymbol cleanup to avoid symbol table churn

### PR DESCRIPTION
**Pull request by olivergillespie**
Hi all,

This pull request contains a backport of commit [d23f4f12](https://github.com/openjdk/jdk/commit/d23f4f12adf1ea26b8c340efe2c3854e50b68301) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Oli Gillespie on 4 Dec 2023 and was reviewed by Coleen Phillimore, Kim Barrett and Aleksey Shipilev.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8315559](https://bugs.openjdk.org/browse/JDK-8315559) needs maintainer approval
- [x] [JDK-8321276](https://bugs.openjdk.org/browse/JDK-8321276) needs maintainer approval

### Issues
 * [JDK-8315559](https://bugs.openjdk.org/browse/JDK-8315559): Delay TempSymbol cleanup to avoid symbol table churn (**Bug** - P3 - Approved)
 * [JDK-8321276](https://bugs.openjdk.org/browse/JDK-8321276): runtime/cds/appcds/dynamicArchive/DynamicSharedSymbols.java failed with "'17 2: jdk/test/lib/apps ' missing from stdout/stderr" (**Bug** - P2 - Approved)

### Reviewers
 * [Coleen Phillimore](https://openjdk.org/census#coleenp) (@coleenp - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/154/head:pull/154` \
`$ git checkout pull/154`

Update a local copy of the PR: \
`$ git checkout pull/154` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/154/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 154`

View PR using the GUI difftool: \
`$ git pr show -t 154`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/154.diff">https://git.openjdk.org/jdk21u-dev/pull/154.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/154#issuecomment-1883419594)

### CODE REVIEW

**Comment by jerboaa** [comment]
@olivergillespie When applying for backports please add a description why that fix is needed in the requested release, what it's risk is and what testing you've done.

Besides, this is a fairly new change and should probably wait for 21.0.4 so that more soak time can be had in JDK 22 before backporting. For now I'll remove the `jdk21u-fix-request` label.

**Comment by olivergillespie** [comment]
/approval request Re-requesting now that it has baked in mainline for a few months, and for parity with 21.0.4-oracle. The backport fixes a performance regression in class-loading which showed up as 5-20% regression in Dacapo pmd benchmark. It is not trivial code, so there is some risk, but with the baking I think it's reasonable. No special testing performed.

**Comment by jerboaa** [comment]
@olivergillespie This looks like it'll need a backport of [JDK-8321276](https://bugs.openjdk.org/browse/JDK-8321276) as well?

**Comment by olivergillespie** [comment]
@jerboaa Yes, thanks for catching, sorry I missed that. I'm not sure the procedure for dependent backports, and I don't have time this week to work on it - I'll try to do so next week if that's okay. I can re-request approval once I have it figured out.

**Comment by GoeLin** [comment]
@olivergillespie, you can includ JDK-8321276 in this change (push an extra commit, add the issue with the /issue command, get a review)
If you backport this to 17, which I think is required, too, you can grab the commit from 21 and get both backported at once.

**Comment by olivergillespie** [comment]
@coleenp any chance you could review this as you were involved with the originals?

**Review by coleenp — APPROVED** [review]
Yes, this looks like a clean backport of the original fix.  Thank you.

**Comment by olivergillespie** [comment]
2 GHA tests failing:

1. Unrelated WhiteBoxResizeTest, fixed by https://github.com/openjdk/jdk21u-dev/pull/381. 
2. Unrelated riscv64 cross-compile build issue. Failing on other PRs.

So I think it's ready to be checked for approval, @jerboaa. Thanks all.

**Comment by olivergillespie** [comment]
/approval JDK-8321276 request Clean backport of test assertion fix, required for the backport of JDK-8315559. Risk is low as it is a change in a test assertion only.

**Pull request closed without merging**
