### PR TITLE
8325469: Freeze/Thaw code can crash in the presence of OSR frames

### PR DESCRIPTION
**Pull request by shipilev**
Unclean backport to fix Loom bug in presence of OSR frames.

The major uncleanliness point comes from [JDK-8329332](https://bugs.openjdk.org/browse/JDK-8329332) that eliminated `CompiledMethod` in JDK 23. But it is only a minor hassle for this PR, as it moves away from `as_compiled_method()` anyway! So I mostly just accepted the incoming chunks untouched.

Additional testing:
 - [x] MacOS AArch64 server fastdebug, new regression test fails without the patch, passes with it
 - [x] MacOS AArch64 server fastdebug, `jdk_loom hotspot_loom`
 - [x] Linux x86_64 server fastdebug, `all`
 - [x] Linux AArch64 server fastdebug, `all`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8325469](https://bugs.openjdk.org/browse/JDK-8325469) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8325469](https://bugs.openjdk.org/browse/JDK-8325469): Freeze/Thaw code can crash in the presence of OSR frames (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/675/head:pull/675` \
`$ git checkout pull/675`

Update a local copy of the PR: \
`$ git checkout pull/675` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/675/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 675`

View PR using the GUI difftool: \
`$ git pr show -t 675`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/675.diff">https://git.openjdk.org/jdk21u-dev/pull/675.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/675#issuecomment-2153030296)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by shipilev** [comment]
/approval request Unclean backport to fix Loom bug in presence of OSR frames. The core of the patch moves num_stack_slots calculation to nmethod, instead of having it in Method; this fixes the OSR discrepancy. Patch does not apply cleanly, requires simple adjustments. All tests pass; new regression test is sensitive to this bug. Risk is low-medium: touches stack computation code, but looks to only affect Virtual Thread paths. Patch was in mainline for 7 weeks without new bugtail.

**Comment by shipilev** [comment]
I realized that while accepting the hunks from the original patch, I accidentally accepted a few minor assert changes. Reverted them here for cleanliness:  https://github.com/openjdk/jdk21u-dev/pull/675/commits/9092002542974c046c1d04f83520e4512983b75f. They should be no-op, as `nmethod` and `CompiledMethod` are rough synonyms. @phohensee -- see if you agree?

**Review by phohensee — APPROVED** [review]
I'd thought the use of is_nmethod intentional since they are indeed pretty much the same. I'm fine either way.

**Pull request closed without merging**
