### PR TITLE
8317446: ProblemList gc/arguments/TestNewSizeFlags.java on macosx-aarch64 in Xcomp

### PR DESCRIPTION
**Pull request by MBaesken**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8317449](https://bugs.openjdk.org/browse/JDK-8317449) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8317446](https://bugs.openjdk.org/browse/JDK-8317446) needs maintainer approval
- [x] [JDK-8334592](https://bugs.openjdk.org/browse/JDK-8334592) needs maintainer approval

### Issues
 * [JDK-8317446](https://bugs.openjdk.org/browse/JDK-8317446): ProblemList gc/arguments/TestNewSizeFlags.java on macosx-aarch64 in Xcomp (**Sub-task** - P4 - Approved)
 * [JDK-8317449](https://bugs.openjdk.org/browse/JDK-8317449): ProblemList serviceability/jvmti/stress/StackTrace/NotSuspended/GetStackTraceNotSuspendedStressTest.java on several platforms (**Sub-task** - P4 - Approved)
 * [JDK-8334592](https://bugs.openjdk.org/browse/JDK-8334592): ProblemList serviceability/jvmti/stress/StackTrace/NotSuspended/GetStackTraceNotSuspendedStressTest.java in jdk21 on all platforms (**Sub-task** - P4 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/829/head:pull/829` \
`$ git checkout pull/829`

Update a local copy of the PR: \
`$ git checkout pull/829` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/829/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 829`

View PR using the GUI difftool: \
`$ git pr show -t 829`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/829.diff">https://git.openjdk.org/jdk21u-dev/pull/829.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/829#issuecomment-2213266226)

### CODE REVIEW

**Review by RealCLanger — CHANGES_REQUESTED** [review]
The issue https://bugs.openjdk.org/browse/JDK-8316392 was already fixed and the fix backported to JDK 21 Updates. So the respective line should be removed and the issue [JDK-8317448](https://bugs.openjdk.org/browse/JDK-8317448) removed from this PR via the "/issue remove" command.

**Comment by MBaesken** [comment]
Should i remove the whole line 
compiler/interpreter/TestVerifyStackAfterDeopt.java 8316392 macosx-aarch64
from the PR ? But then it would not be clean any more.

**Comment by RealCLanger** [comment]
Could you please also add [JDK-8334592](https://bugs.openjdk.org/browse/JDK-8334592) to this PR for the bookkeeping? I understand that that's the actual issue that we want to do in JDK 21 updates for Oracle parity. Thanks.

**Review by RealLucy — APPROVED** [review]
Looks good.

**Pull request closed without merging**
