### PR TITLE
8330011: [s390x] update block-comments to make code consistent

### PR DESCRIPTION
**Pull request by offamitkumar**
Hi all,

This pull request contains a backport of commit [01bda278](https://github.com/openjdk/jdk/commit/01bda278d6a498ca89c0bc5218680cd51a04e9d3) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Amit Kumar on 17 Apr 2024 and was reviewed by Lutz Schmidt.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8330011](https://bugs.openjdk.org/browse/JDK-8330011) needs maintainer approval

### Issue
 * [JDK-8330011](https://bugs.openjdk.org/browse/JDK-8330011): [s390x] update block-comments to make code consistent (**Bug** - P4 - Approved)

### Reviewers
 * [Lutz Schmidt](https://openjdk.org/census#lucy) (@RealLucy - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/539/head:pull/539` \
`$ git checkout pull/539`

Update a local copy of the PR: \
`$ git checkout pull/539` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/539/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 539`

View PR using the GUI difftool: \
`$ git pr show -t 539`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/539.diff">https://git.openjdk.org/jdk21u-dev/pull/539.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/539#issuecomment-2080378445)

### CODE REVIEW

**Comment by offamitkumar** [comment]
@RealLucy would you take a quick look here as well. In this I had to modify the comments manually there were some other conflicts as well other than copyright header.

But still it only updates the comments , and minor c++ code alignment fix.

**Review by RealLucy — APPROVED** [review]
LGTM.

**Comment by GoeLin** [comment]
Hi Amit, here also tests are missing. Also, please elaborate on the Risk in your fix-request comments.

**Comment by offamitkumar** [comment]
/backport request Had to backport this change as Panama was ported in JDK-21 so comment needs to updated in JDK-21 repo as well. As only comments are being updated so risk here is low.

**Comment by offamitkumar** [comment]
/approval request Had to backport this change as Panama was ported in JDK-21 so comment needs to updated in JDK-21 repo as well. As only comments are being updated. So risk here is low.

**Pull request closed without merging**
