### PR TITLE
8316959: Improve InlineCacheBuffer pending queue management

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 21.0.4-oracle.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8316959](https://bugs.openjdk.org/browse/JDK-8316959) needs maintainer approval

### Issue
 * [JDK-8316959](https://bugs.openjdk.org/browse/JDK-8316959): Improve InlineCacheBuffer pending queue management (**Enhancement** - P4 - Approved)

### Reviewers
 * [Roland Westrelin](https://openjdk.org/census#roland) (@rwestrel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/453/head:pull/453` \
`$ git checkout pull/453`

Update a local copy of the PR: \
`$ git checkout pull/453` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/453/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 453`

View PR using the GUI difftool: \
`$ git pr show -t 453`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/453.diff">https://git.openjdk.org/jdk21u-dev/pull/453.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/453#issuecomment-2039150761)

### CODE REVIEW

**Comment by GoeLin** [comment]
GHA failures: Tests did not run at all. Others could not upload the results. Infra issue seen with several PRs lately. Unrelated. 
Same tests were run in SAPs internal testing infra.

**Comment by jerboaa** [comment]
@rwestrel Could you please help review this? Is that OK going into JDK 21 in your opinion?

**Review by rwestrel — APPROVED** [review]
Looks good to me.

**Comment by jerboaa** [comment]
Thanks!

**Pull request closed without merging**
