### PR TITLE
8316138: Add GlobalSign 2 TLS root certificates

### PR DESCRIPTION
**Pull request by Delawen**
Backport from https://bugs.openjdk.org/browse/JDK-8316138

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8316138](https://bugs.openjdk.org/browse/JDK-8316138) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316138](https://bugs.openjdk.org/browse/JDK-8316138): Add GlobalSign 2 TLS root certificates (**Enhancement** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/581/head:pull/581` \
`$ git checkout pull/581`

Update a local copy of the PR: \
`$ git checkout pull/581` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/581/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 581`

View PR using the GUI difftool: \
`$ git pr show -t 581`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/581.diff">https://git.openjdk.org/jdk21u-dev/pull/581.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/581#issuecomment-2117212041)

### CODE REVIEW

**Comment by Delawen** [comment]
```
$ make test TEST="jdk_security"  | grep VerifyCACerts
Passed: sun/security/lib/cacerts/VerifyCACerts.java
```

**Comment by Delawen** [comment]
/approval JDK-8316138 request Fix Request
This is a backport for https://bugs.openjdk.org/browse/JDK-8316138 It includes two new certificates for cacert. It also updates the test that checks certificates are in place.

**Comment by Delawen** [comment]
@jerboaa Can you review this? There is still a test running in MacOS that failed yesterday, but I think it is not related to my change.

The test that checks the certificates runs properly on my local machine:
```
$ make test TEST="jdk_security"  | grep VerifyCACerts
Passed: sun/security/lib/cacerts/VerifyCACerts.java```

**Comment by jerboaa** [comment]
@Delawen Please also run the CA tests in `CertPathValidator/certification` test. Thanks!

**Pull request closed without merging**
