### PR TITLE
8320192: SHAKE256 does not work correctly if n >= 137

### PR DESCRIPTION
**Pull request by dchuyko**
This is a backport of KAT fix for SHAKE256. The test provided in the bug description currently fails on JDK 21. SHA3 part is clean, SHAKE128 part is removed as it is a separate new API.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8320192](https://bugs.openjdk.org/browse/JDK-8320192) needs maintainer approval

### Issue
 * [JDK-8320192](https://bugs.openjdk.org/browse/JDK-8320192): SHAKE256 does not work correctly if n &gt;= 137 (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/902/head:pull/902` \
`$ git checkout pull/902`

Update a local copy of the PR: \
`$ git checkout pull/902` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/902/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 902`

View PR using the GUI difftool: \
`$ git pr show -t 902`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/902.diff">https://git.openjdk.org/jdk21u-dev/pull/902.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/902#issuecomment-2275942882)

### CODE REVIEW

**Comment by dchuyko** [comment]
/approval request This is a clean backport. The change improves NIST CAVP conformance for SHAKE256 algorithm. The test provided in the bug description currently fails on JDK 21 and passes after patching.

Testing: provided "A2" test, test/jdk/java/security jtreg.

**Comment by jerboaa** [comment]
This also adds `SHAKE128.java`, which I  believe isn't needed for this bug-fix. Please remove it and get it reviewed.

**Comment by dchuyko** [comment]
Thanks, Severin. I missed that the class is public, now it's removed from the backport.

**Review by phohensee — APPROVED** [review]

**Comment by dchuyko** [comment]
/approval request The change improves NIST CAVP conformance for SHAKE256 algorithm. The test provided in the bug description currently fails on JDK 21 and passes after patching. SHA3 part is clean, SHAKE128 part is removed.

Testing: provided "A2" test, test/jdk/java/security jtreg.

**Pull request closed without merging**
