### PR TITLE
8317809: Insertion of free code blobs into code cache can be very slow during class unloading

### PR DESCRIPTION
**Pull request by GoeLin**
Big change, but only two resolves needed:

src/hotspot/share/gc/g1/g1ConcurrentMark.cpp
The context differs because "8309538: G1: Move total collection increment from Cleanup to Remark"
is only in 22

src/hotspot/share/gc/serial/genMarkSweep.cpp
Resolved adding an #include.

SAP nightly testing passed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8317809](https://bugs.openjdk.org/browse/JDK-8317809) needs maintainer approval

### Issue
 * [JDK-8317809](https://bugs.openjdk.org/browse/JDK-8317809): Insertion of free code blobs into code cache can be very slow during class unloading (**Enhancement** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew Dinn](https://openjdk.org/census#adinn) (@adinn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/505/head:pull/505` \
`$ git checkout pull/505`

Update a local copy of the PR: \
`$ git checkout pull/505` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/505/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 505`

View PR using the GUI difftool: \
`$ git pr show -t 505`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/505.diff">https://git.openjdk.org/jdk21u-dev/pull/505.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/505#issuecomment-2066349008)

### CODE REVIEW

**Comment by GoeLin** [comment]
GHA failure: x86 (32-bit) test failure in gc/g1/humongousObjects/TestHumongousClassLoader.java

2024-04-16T11:19:19.7475339Z Loading class TwoRegionHumongousClass
2024-04-16T11:19:19.7475888Z #
2024-04-16T11:19:19.7476442Z # A fatal error has been detected by the Java Runtime Environment:
2024-04-16T11:19:19.7477171Z #
2024-04-16T11:19:19.7477620Z #  SIGSEGV (0xb) at pc=0xe94303d7, pid=17327, tid=17350
2024-04-16T11:19:19.7478227Z #
2024-04-16T11:19:19.7479030Z # JRE version: OpenJDK Runtime Environment (21.0.4) (fastdebug build 21.0.4-internal-GoeLin-8a29893d2c8ecee5209cbddc90317fe74ca810fd)
2024-04-16T11:19:19.7480380Z # Java VM: OpenJDK Server VM (fastdebug 21.0.4-internal-GoeLin-8a29893d2c8ecee5209cbddc90317fe74ca810fd, mixed mode, sharing, tiered, g1 gc, linux-x86)
2024-04-16T11:19:19.7481197Z # Problematic frame:
2024-04-16T11:19:19.7493177Z # V  [libjvm.so+0x2303d7]  oopDesc::size_given_klass(Klass*)+0x17
2024-04-16T11:19:19.7493635Z #
2024-04-16T11:19:19.7493927Z # CreateCoredumpOnCrash turned off, no core file dumped
2024-04-16T11:19:19.7494317Z #
2024-04-16T11:19:19.7494585Z Unsupported internal testing APIs have been used.
2024-04-16T11:19:19.7494877Z 
2024-04-16T11:19:19.7495063Z # An error report file with more information is saved as:
2024-04-16T11:19:19.7496084Z # /home/runner/work/jdk21u-dev/jdk21u-dev/build/run-test-prebuilt/test-support/jtreg_test_hotspot_jtreg_tier1_gc/scratch/1/hs_err_pid17327.log
2024-04-16T11:19:19.7496854Z #
2024-04-16T11:19:19.7497143Z # If you would like to submit a bug report, please visit:
2024-04-16T11:19:19.7497615Z #   https://bugreport.java.com/bugreport/crash.jsp

**Review by phohensee — APPROVED** [review]

**Review by phohensee — COMMENTED** [review]
TwoRegionHumongousClass failed with "Unsupported internal testing APIs have been used."

**Comment by GoeLin** [comment]
Backporting the prereqs helped, tests are green now.

**Comment by GoeLin** [comment]
@tschatzl would you mind to take a look at this change?

Especially as you had to backout ([JDK-8329524](https://bugs.openjdk.org/browse/JDK-8329524)/[JDK-8329530](https://bugs.openjdk.org/browse/JDK-8329530)) your first backport, is there a subtle adaption needed I missed?

Thanks! Goetz.

**Comment by adinn** [comment]
@jerboaa Looks ok to me.

**Comment by tschatzl** [comment]
> Especially as you had to backout ([JDK-8329524](https://bugs.openjdk.org/browse/JDK-8329524)/[JDK-8329530](https://bugs.openjdk.org/browse/JDK-8329530)) your first backport, is there a subtle adaption needed I missed?

The backport was due to wrongly resolving the hunk in g1ConcurrentMark.cpp. Afaict that issue has been resolved correctly.

**Comment by GoeLin** [comment]
Thanks for having a look, @tschatzl!  Best regards, Goetz.

**Pull request closed without merging**
