### PR TITLE
8317535: Shenandoah: Remove unused code

### PR DESCRIPTION
**Pull request by earthling-amzn**
Removes unused and/or unreachable code.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8317535](https://bugs.openjdk.org/browse/JDK-8317535) needs maintainer approval

### Issue
 * [JDK-8317535](https://bugs.openjdk.org/browse/JDK-8317535): Shenandoah: Remove unused code (**Task** - P4 - Approved)

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - no project role)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/194/head:pull/194` \
`$ git checkout pull/194`

Update a local copy of the PR: \
`$ git checkout pull/194` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/194/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 194`

View PR using the GUI difftool: \
`$ git pr show -t 194`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/194.diff">https://git.openjdk.org/jdk21u-dev/pull/194.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/194#issuecomment-1898872810)

### CODE REVIEW

**Comment by earthling-amzn** [comment]
/approval request This was almost a clean backport, the merge conflict was trivial to resolve. This change only removes code that was unused and everything still compiles. Additionally, we've tested this change on Dacapo, Heapothesys, Extremem, SpecJBB and SpecJVM.

**Review by kdnilsen — APPROVED** [review]
Thanks for this cleanup.

**Review by ysramakrishna — APPROVED** [review]

**Pull request closed without merging**
