### PR TITLE
8319124: Update XML Security for Java to 3.0.3

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 21.0.3-oracle.

The patch applied clean (first commit).

I removed the strings from SignatureMethod.java as documented in the backport CSR.
I did not change DOMSignatureMethod.java.

I skipped the changes to GenerationTest.java. The test passes.

**Update**: 
I pushed a new commit that makes the four new test cases work.
As proposed in the CSR, I use the plain strings instead of the constants defined in SignatureMethod.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8319124](https://bugs.openjdk.org/browse/JDK-8319124) needs maintainer approval
- [x] Change requires CSR request [JDK-8321532](https://bugs.openjdk.org/browse/JDK-8321532) to be approved

### Issues
 * [JDK-8319124](https://bugs.openjdk.org/browse/JDK-8319124): Update XML Security for Java to 3.0.3 (**Enhancement** - P3 - Approved)
 * [JDK-8321532](https://bugs.openjdk.org/browse/JDK-8321532): Update XML Security for Java to 3.0.3 (**CSR**)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/94/head:pull/94` \
`$ git checkout pull/94`

Update a local copy of the PR: \
`$ git checkout pull/94` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/94/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 94`

View PR using the GUI difftool: \
`$ git pr show -t 94`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/94.diff">https://git.openjdk.org/jdk21u-dev/pull/94.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/94#issuecomment-1868315945)

### CODE REVIEW

**Comment by MBaesken** [comment]
Hi Goetz , looks mostly good.
But I am not sure about this change 

src/java.xml.crypto/share/classes/org/jcp/xml/dsig/internal/dom/DOMXMLSignatureFactory.java

        } else if (algorithm.equals(DOMSignatureMethod.RSA_SHA3_224_MGF1)) {
            return new DOMSignatureMethod.SHA3_224withRSAandMGF1(params);
        } else if (algorithm.equals(DOMSignatureMethod.RSA_SHA3_256_MGF1)) {
            return new DOMSignatureMethod.SHA3_256withRSAandMGF1(params);
        } else if (algorithm.equals(DOMSignatureMethod.RSA_SHA3_384_MGF1)) {
            return new DOMSignatureMethod.SHA3_384withRSAandMGF1(params);
        } else if (algorithm.equals(DOMSignatureMethod.RSA_SHA3_512_MGF1)) {
            return new DOMSignatureMethod.SHA3_512withRSAandMGF1(params);

here you reference new algorithms from higher jdk versions; should they really be present here in jdk21 ?

**Comment by GoeLin** [comment]
> Hi Goetz , looks mostly good. But I am not sure about this change
> 
> src/java.xml.crypto/share/classes/org/jcp/xml/dsig/internal/dom/DOMXMLSignatureFactory.java
> 
> ```
>     } else if (algorithm.equals(DOMSignatureMethod.RSA_SHA3_224_MGF1)) {
>         return new DOMSignatureMethod.SHA3_224withRSAandMGF1(params);
>     } else if (algorithm.equals(DOMSignatureMethod.RSA_SHA3_256_MGF1)) {
>         return new DOMSignatureMethod.SHA3_256withRSAandMGF1(params);
>     } else if (algorithm.equals(DOMSignatureMethod.RSA_SHA3_384_MGF1)) {
>         return new DOMSignatureMethod.SHA3_384withRSAandMGF1(params);
>     } else if (algorithm.equals(DOMSignatureMethod.RSA_SHA3_512_MGF1)) {
>         return new DOMSignatureMethod.SHA3_512withRSAandMGF1(params);
> ```
> 
> here you reference new algorithms from higher jdk versions; should they really be present here in jdk21 ?

I left this in the code because the CSR says "but the underlying implementation code will be integrated for use via the XML signature implementation."  There is also code in DOMSignatureMethod.java mentioning the new algs.

But I am not sure this is the code that is meant by that note.

**Comment by MBaesken** [comment]
> I use the plain strings instead of the constants defined in SignaturMethod.

Little typo, SignatureMethod .  Yes I think this is correct according to the CSR for older releases https://bugs.openjdk.org/browse/JDK-8321532 .

**Review by MBaesken — APPROVED** [review]

**Comment by GoeLin** [comment]
GHA tests had been clean before I updated the test.

**Pull request closed without merging**
