### PR TITLE
8330520: linux clang build fails in os_linux.cpp with static_assert with no message is a C++17 extension

### PR DESCRIPTION
**Pull request by varada1110**
Hi all,

This pull request contains a backport of commit [4b55fe57](https://github.com/openjdk/jdk/commit/4b55fe577701317e6570f045ed9fe28aa97fc7ea) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Matthias Baesken on 18 Apr 2024 and was reviewed by Stefan Karlsson and Martin Doerr.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8330520](https://bugs.openjdk.org/browse/JDK-8330520) needs maintainer approval

### Warning
&nbsp;⚠️ Found leading lowercase letter in issue title for `8330520: linux clang build fails in os_linux.cpp with static_assert with no message is a C++17 extension`

### Issue
 * [JDK-8330520](https://bugs.openjdk.org/browse/JDK-8330520): linux clang build fails in os_linux.cpp with static_assert with no message is a C++17 extension (**Bug** - P4 - Approved)

### Reviewers
 * [Martin Doerr](https://openjdk.org/census#mdoerr) (@TheRealMDoerr - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/876/head:pull/876` \
`$ git checkout pull/876`

Update a local copy of the PR: \
`$ git checkout pull/876` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/876/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 876`

View PR using the GUI difftool: \
`$ git pr show -t 876`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/876.diff">https://git.openjdk.org/jdk21u-dev/pull/876.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/876#issuecomment-2257561737)

### CODE REVIEW

**Comment by varada1110** [comment]
/approval 8330520 request build error observed with clang on linux is resolved. Build and tier1 testing successful

**Review by TheRealMDoerr — APPROVED** [review]
This backport contains a part of https://github.com/openjdk/jdk/commit/3699666c9325b38d287e1d4d2576f8e3a662ae81. I think it is ok because it is only preprocessor stuff.

**Comment by varada1110** [comment]
Thank you
/integrate

**Comment by TheRealMDoerr** [comment]
Can you enable the GHA pre-submit tests, please?

**Comment by varada1110** [comment]
Hi Martin, I enabled GHA and all checks have passed

**Pull request closed without merging**
