### PR TITLE
8311964: Some jtreg tests failing on x86 with error 'unrecognized VM options' (C2 flags)

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi,

Clean backport of [JDK-8311964](https://github.com/openjdk/jdk/pull/14942). Backport has been verified as bellow. Only change the testcases, the risk is low.

There 3 testcases run complaint "Unrecognized VM option" with linux-x86-client-release jdk before this PR. LoopUnswitching, OptimizeFill and StressCCP are all C2 flags.
test command:
```shell
rm -rf tmp/ ; jtreg -v:fail,error -nr -w tmp -jdk:build/linux-x86-client-release/images/jdk/ test/hotspot/jtreg/compiler/loopopts/TestBackedgeLoadArrayFillMain.java test/hotspot/jtreg/compiler/loopopts/TestInfiniteLoopWithUnmergedBackedgesMain.java test/hotspot/jtreg/compiler/rangechecks/TestRangeCheckCmpUOverflowVsSub.java 2>&1 | grep "Unrecognized VM option"
```
image

After this PR, there 3 testcases won't be selected when the test jdk is linux-x86-client.
image

Thanks,
-sendao

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8311964](https://bugs.openjdk.org/browse/JDK-8311964) needs maintainer approval

### Issue
 * [JDK-8311964](https://bugs.openjdk.org/browse/JDK-8311964): Some jtreg tests failing on x86 with error 'unrecognized VM options' (C2 flags) (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/279/head:pull/279` \
`$ git checkout pull/279`

Update a local copy of the PR: \
`$ git checkout pull/279` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/279/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 279`

View PR using the GUI difftool: \
`$ git pr show -t 279`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/279.diff">https://git.openjdk.org/jdk21u-dev/pull/279.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/279#issuecomment-1956552371)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi @sendaoYan 
Same as with your orther request. The comment is missing. Please read https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix
I won't check and comment all of your backports, instead I will remove the tag of all the ones I find today.  Please double check all of them, you find a list here: https://github.com/pulls if you are logged in to github.

**Comment by sendaoYan** [comment]
> Hi @sendaoYan Same as with your orther request. The comment is missing. Please read https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix I won't check and comment all of your backports, instead I will remove the tag of all the ones I find today. Please double check all of them, you find a list here: https://github.com/pulls if you are logged in to github.

Thanks, I will check all mine PR there few days.

**Comment by sendaoYan** [comment]
> Hi @sendaoYan Same as with your orther request. The comment is missing. Please read https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix I won't check and comment all of your backports, instead I will remove the tag of all the ones I find today. Please double check all of them, you find a list here: https://github.com/pulls if you are logged in to github.

Thanks, I will check all mine PRs there few days.

**Comment by sendaoYan** [comment]
> Hi @sendaoYan Same as with your orther request. The comment is missing. Please read https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix I won't check and comment all of your backports, instead I will remove the tag of all the ones I find today. Please double check all of them, you find a list here: https://github.com/pulls if you are logged in to github.

Thanks, I will check all mine openjdk PRs these few days.

**Comment by sendaoYan** [comment]
/approval JDK-8311964 request "Clean backport. Backport has been verified. Only change the testcases, the risk is low."

**Comment by shipilev** [comment]
I think is PR base is too old, bot says there are 318 commits ahead of it. Can you please merge from master to see if it still works?

**Comment by sendaoYan** [comment]
> I think is PR base is too old, bot says there are 318 commits ahead of it. Can you please merge from master to see if it still works?

I have merged from master just now. Thanks for the advice.

**Comment by sendaoYan** [comment]
> /sponsor

Thanks.

**Pull request closed without merging**
