### PR TITLE
8322166: Files.isReadable/isWritable/isExecutable expensive when file does not exist

### PR DESCRIPTION
**Pull request by toddjonker**
Clean backport of a performance fix, originally authored by @bplb and reviewed by @AlanBateman 

Test suites run on linux-x86_64-server-release:
- [x] tier1
- [x] jdk/java/nio

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8322166](https://bugs.openjdk.org/browse/JDK-8322166) needs maintainer approval

### Issue
 * [JDK-8322166](https://bugs.openjdk.org/browse/JDK-8322166): Files.isReadable/isWritable/isExecutable expensive when file does not exist (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/926/head:pull/926` \
`$ git checkout pull/926`

Update a local copy of the PR: \
`$ git checkout pull/926` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/926/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 926`

View PR using the GUI difftool: \
`$ git pr show -t 926`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/926.diff">https://git.openjdk.org/jdk21u-dev/pull/926.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/926#issuecomment-2293694489)

### CODE REVIEW

**Comment by toddjonker** [comment]
/approval request Clean backport of a performance fix; originally authored by @bplb and reviewed by @AlanBateman

**Comment by jerboaa** [comment]
This hasn't been in any released JDK version. Deferred to 21.0.6.

**Pull request closed without merging**
