### PR TITLE
8337876: [IR Framework] Add support for IR tests with @Stable

### PR DESCRIPTION
**Pull request by shipilev**
Improves IR test framework in preparation for `@Stable` fixes.

Additional testing:
 - [x] MacOS AArch64 server fastdebug, `testlibrary_tests/ir_framework/tests compiler/c2/irTests`
 - [x] MacOS AArch64 server release, `testlibrary_tests/ir_framework/tests compiler/c2/irTests`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8338112](https://bugs.openjdk.org/browse/JDK-8338112) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8337876](https://bugs.openjdk.org/browse/JDK-8337876) needs maintainer approval

### Issues
 * [JDK-8337876](https://bugs.openjdk.org/browse/JDK-8337876): [IR Framework] Add support for IR tests with @Stable (**Enhancement** - P4 - Approved)
 * [JDK-8338112](https://bugs.openjdk.org/browse/JDK-8338112): Test testlibrary_tests/ir_framework/tests/TestPrivilegedMode.java fails with release build (**Bug** - P4 - Approved)

### Reviewers
 * [Evgeny Astigeevich](https://openjdk.org/census#eastigeevich) (@eastig - Author)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21u-dev.git pull/1043/head:pull/1043` \
`$ git checkout pull/1043`

Update a local copy of the PR: \
`$ git checkout pull/1043` \
`$ git pull https://git.openjdk.org/jdk21u-dev.git pull/1043/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1043`

View PR using the GUI difftool: \
`$ git pr show -t 1043`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21u-dev/pull/1043.diff">https://git.openjdk.org/jdk21u-dev/pull/1043.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21u-dev/pull/1043#issuecomment-2404652368)

### CODE REVIEW

**Comment by shipilev** [comment]
Both backports are clean, they are in the same PR so that we keep the tests clean.

/clean

**Comment by shipilev** [comment]
/approval 8337876 Adds infrastructural support for more IR tests. Applies cleanly. New tests pass, needs JDK-8338112 as the testbug followup. Risk is low, test infrastructure change.
/approval 8338112 Test bugfix for JDK-8337876, applies cleanly. Tests pass with both fastdebug and release builds. Risk is low.

**Comment by shipilev** [comment]
> Looks clean backport to me.

Thanks!

**Review by phohensee — APPROVED** [review]

**Comment by shipilev** [comment]
Thanks!

/integrate

**Pull request closed without merging**
